packages:
  - core
  - services
  - map
  - map-integration-tests

# https://pnpm.io/catalogs
catalog:
  "@types/lodash-es": ^4.17.12
  "@vitest/coverage-v8": ^3.2.4
  lodash-es: ^4.17.21
  maplibre-gl: ">=5.6.1"
  typescript: ^5.9.2
  vite: ^7.1.0
  vitest: ^3.2.4
  vite-plugin-dts: ^4.5.4
