packages:
  - shared-configs
  - core
  - services
  - map
  - map-integration-tests
  - examples/**

catalog:
  '@tsconfig/recommended': ^1.0.10
  '@types/geojson': ^7946.0.16
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24.7.0
  '@vitest/coverage-v8': ^3.2.4
  lodash-es: ^4.17.21
  maplibre-gl: ^5.9.0
  rimraf: ^6.0.1
  rollup-plugin-visualizer: ^6.0.4
  ts-node: ^10.9.2
  typescript: ^5.9.3
  vite: ^7.1.9
  vite-plugin-dts: ^4.5.4
  vitest: ^3.2.4
