packages:
  - shared-configs
  - core
  - services
  - map
  - map-integration-tests
  - plugins/**
  - examples/**

catalog:
  '@codesandbox/sandpack-react': ^2.20.0
  '@codesandbox/sandpack-themes': ^2.0.21
  '@microsoft/api-extractor': ^7.56.3
  '@playwright/test': ^1.58.2
  '@tsconfig/recommended': ^1.0.13
  '@turf/turf': ^7.3.4
  '@types/geojson': ^7946.0.16
  '@types/lodash-es': ^4.17.12
  '@types/node': ^25.2.3
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@types/rollup-plugin-peer-deps-external': ^2.2.6
  '@vitejs/plugin-react': ^5.1.4
  '@vitest/coverage-v8': ^4.0.18
  jsdom: ^28.0.0
  lodash-es: ^4.17.23
  maplibre-gl: ^5.18.0
  react: ^19.2.4
  react-dom: ^19.2.4
  rimraf: ^6.1.3
  rollup-plugin-analyzer: ^4.0.0
  rollup-plugin-license: ^3.7.0
  rollup-plugin-peer-deps-external: ^2.2.4
  rollup-plugin-visualizer: ^6.0.5
  ts-node: ^10.9.2
  typescript: ^5.9.3
  vite: ^7.3.1
  vite-plugin-dts: 5.0.0-beta.6
  vite-plugin-singlefile: ^2.3.0
  vitest: ^4.0.18
  zod: ^4.3.6

ignoredBuiltDependencies:
  - esbuild
