packages:
  - shared-configs
  - core
  - services
  - map
  - map-integration-tests
  - examples/**

catalog:
  '@codesandbox/sandpack-react': ^2.20.0
  '@codesandbox/sandpack-themes': ^2.0.21
  '@microsoft/api-extractor': ^7.55.2
  '@tsconfig/recommended': ^1.0.13
  '@turf/turf': ^7.3.1
  '@types/geojson': ^7946.0.16
  '@types/lodash-es': ^4.17.12
  '@types/node': ^25.0.2
  '@types/node': ^25.0.0
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/coverage-v8': ^4.0.15
  lodash-es: ^4.17.21
  maplibre-gl: ^5.14.0
  react: ^19.2.1
  react-dom: ^19.2.1
  rimraf: ^6.1.2
  rollup-plugin-analyzer: ^4.0.0
  rollup-plugin-license: ^3.6.0
  rollup-plugin-visualizer: ^6.0.5
  ts-node: ^10.9.2
  typescript: ^5.9.3
  vite: ^7.3.0
  vite-plugin-dts: 5.0.0-beta.6
  vite-plugin-singlefile: ^2.3.0
  vitest: ^4.0.15
