packages:
  - core
  - services
  - map
  - map-integration-tests

catalog:
  '@types/lodash-es': ^4.17.12
  '@vitest/coverage-v8': ^3.2.4
  lodash-es: ^4.17.21
  maplibre-gl: '>=5.6.2'
  typescript: ^5.9.2
  vite: ^7.1.3
  vite-plugin-dts: ^4.5.4
  vitest: ^3.2.4
