/**
 * @ignore
 */
export const poiClassificationToIconID = {
    ACCESS_GATEWAY: 310,
    ADVENTURE_SPORTS_VENUE: 322,
    AGRICULTURE: 307,
    AGRICULTURE_BUSINESS: 307,
    AIRPORT: 141,
    AMUSEMENT_PARK: 173,
    ASHRAM: 160,
    ATM: 242,
    AUTOMOTIVE_DEALER: 314,
    BANK: 277,
    BEACH: 243,
    BUILDING_POINT: 132, // no 132 icon mapping in map sprites
    BUSINESS_PARK: 302,
    CAFE_PUB: 320,
    CAMPING_GROUND: 258,
    CAR_WASH: 267,
    CASH_DISPENSER: 242,
    CASINO: 209,
    CHURCH: 155,
    CINEMA: 211,
    CITY_CENTER: 12, // no 12 icon mapping in map sprites
    CLUB_ASSOCIATION: 331,
    COLLEGE_UNIVERSITY: 156,
    COMMERCIAL_BUILDING: 298,
    COMMUNITY_CENTER: 281,
    COMPANY: 213,
    CONCERT_HALL: 250,
    COURTHOUSE: 215,
    CULTURAL_CENTER: 216,
    DENTIST: 248,
    DEPARTMENT_STORE: 304,
    DOCTOR: 247,
    ELECTRIC_VEHICLE_STATION: 273,
    EMBASSY: 240,
    EMERGENCY_MEDICAL_SERVICE: 315,
    EMERGENCY_ROOM: 315,
    ENTERTAINMENT: 235,
    EXCHANGE: 296,
    EXHIBITION_CONVENTION_CENTER: 217,
    FERRY_TERMINAL: 145,
    FIRE_STATION_BRIGADE: 164,
    FRONTIER_CROSSING: 219,
    FUEL_FACILITIES: 204,
    GAS_STATION: 204,
    GEOGRAPHIC_FEATURE: 127,
    GOLF_COURSE: 171,
    GOVERNMENT_OFFICE: 166,
    GURUDWARA: 160,
    HEALTH_CARE_SERVICE: 316,
    HELIPAD: 323,
    HELIPAD_HELICOPTER_LANDING: 323,
    HILL: 158,
    HOLIDAY_RENTAL: 330,
    HOSPITAL: 157,
    HOSPITAL_POLYCLINIC: 157,
    HOTEL_MOTEL: 222,
    ICE_SKATING_RINK: 244,
    IMPORTANT_TOURIST_ATTRACTION: 154,
    INDUSTRIAL_BUILDING: 172,
    LEISURE_CENTER: 321,
    LIBRARY: 252,
    MANUFACTURING_FACILITY: 299,
    MARINA: 262,
    MARKET: 318,
    MEDIA_FACILITY: 301,
    MILITARY_INSTALLATION: 170,
    MOSQUE: 160,
    MOTORING_ORGANIZATION_OFFICE: 276,
    MOUNTAIN_PASS: 224,
    MOUNTAIN_PEAK: 158,
    MOVIE_THEATER: 211,
    MUSEUM: 176,
    NATIVE_RESERVATION: 325,
    NIGHTLIFE: 250,
    NON_GOVERNMENTAL_ORGANIZATION: 334,
    OPEN_PARKING_AREA: 159,
    OPERA: 235,
    PAGODA: 160,
    PARK_RECREATION_AREA: 169,
    PARKING_GARAGE: 203,
    PETROL_STATION: 204,
    PHARMACY: 254,
    PLACE_OF_WORSHIP: 155,
    POLICE_STATION: 161,
    PORT_WAREHOUSE_FACILITY: 305,
    POST_CODE: 63, // no 63 icon mapping in map sprites
    POST_OFFICE: 165,
    PRIMARY_RESOURCE_UTILITY: 308,
    PRISON_CORRECTIONAL_FACILITY: 167,
    PUBLIC_AMENITY: 297,
    PUBLIC_TRANSPORT_STOP: 142,
    RAILROAD_STATION: 147,
    RAILWAY_STATION: 147,
    RENT_A_CAR_FACILITY: 229,
    RENT_A_CAR_PARKING: 230,
    REPAIR_FACILITY: 253,
    RESEARCH_FACILITY: 300,
    RESIDENTIAL_ACCOMMODATION: 303,
    REST_AREA: 206,
    RESTAURANT: 231,
    RESTAURANT_AREA: 31,
    SCENIC_PANORAMIC_VIEW: 255,
    SCHOOL: 156,
    SHOP: 162,
    SHOPPING_CENTER: 163,
    SPORTS_CENTER: 238,
    STADIUM: 177,
    SWIMMING_POOL: 256,
    SYNAGOG: 160,
    TEMPLE: 160,
    TENNIS_COURT: 45,
    THEATER: 235,
    TOLL_GATE: 284,
    TOURIST_INFORMATION_OFFICE: 236,
    TRAFFIC_LIGHT: 129, // no 129 icon mapping in map sprites
    TRAFFIC_SERVICE_CENTER: 326,
    TRAFFIC_SIGN: 128, // no 128 icon mapping in map sprites
    TRAIL_SYSTEM: 324,
    TRANSPORT_AUTHORITY_VEHICLE_REGISTRATION: 313,
    TRUCK_STOP: 312,
    VACATION_RENTAL: 330,
    VETERINARIAN: 249,
    WATER_SPORT: 246,
    WEIGH_STATION: 311,
    WELFARE_ORGANIZATION: 317,
    WINERY: 257,
    ZOOS_ARBORETA_BOTANICAL_GARDEN: 168
};

export const searchToPOILayerClassificationMapping: Record<string, string> = {
    cafe_pub: "cafe_or_pub",
    exhibition_convention_center: "exhibition_and_convention_center",
    college_university: "college_or_university",
    fire_station_brigade: "fire_station_or_brigade",
    primary_resource_utility: "primary_resource_or_utility",
    prison_correctional_facility: "prison_or_correctional_facility",
    transport_authority_vehicle_registration: "transport_authority_or_vehicle_registration",
    club_association: "club_and_association",
    park_recreation_area: "park_and_recreation_area",
    zoos_arboreta_botanical_garden: "zoo_arboreta_and_botanical_garden",
    hotel_motel: "hotel_or_motel",
    residential_accommodation: "residential_accommodations",
    important_tourist_attraction: "tourist_attraction",
    scenic_panoramic_view: "scenic_or_panoramic_view",
    port_warehouse_facility: "port_or_warehouse_facility",
    public_transport_stop: "public_transportation_stop",
    ashram: "place_of_worship",
    church: "place_of_worship",
    gurudwara: "place_of_worship",
    mosque: "place_of_worship",
    pagoda: "place_of_worship",
    synagog: "place_of_worship",
    temple: "place_of_worship",
    mountain_peak: "geographic_feature",
    hill: "geographic_feature",
    railway_station: "railroad_station",
    petrol_station: "gas_station",
    fuel_facilities: "gas_station",
    cash_dispenser: "atm",
    cinema: "movie_theater",
    agriculture: "agriculture_business",
    concert_hall: "nightlife",
    helipad_helicopter_landing: "helipad",
    opera: "theater",
    holiday_rental: "vacation_rental",
    hospital_polyclinic: "hospital"
};

/**
 * @ignore
 */
export const poiClassificationFromIconID = (iconID: number) => {
    return Object.keys(poiClassificationToIconID).find(
        (key) => poiClassificationToIconID[key as POIClassification] === iconID
    );
};

export type POIClassification = keyof typeof poiClassificationToIconID;
