import { formatDuration, formatMeters } from "../UnitFormatters";

describe("Unit formatters tests", () => {
    test("format duration", () => {
        expect(formatDuration(0)).toBeNull();
        expect(formatDuration(20)).toBeNull();
        expect(formatDuration(30)).toBe("1 min");
        expect(formatDuration(60)).toBe("1 min");
        expect(formatDuration(100)).toBe("2 min");
        expect(formatDuration(3600)).toBe("1 hr 00 min");
        expect(formatDuration(3599)).toBe("1 hr 00 min");
        expect(formatDuration(3540)).toBe("59 min");
        expect(formatDuration(3570)).toBe("1 hr 00 min");
        expect(formatDuration(3660)).toBe("1 hr 01 min");
        expect(formatDuration(36120)).toBe("10 hr 02 min");
    });

    test("format meters", () => {
        expect(formatMeters(0, "metric")).toBe("0 m");
        expect(formatMeters(2, "metric")).toBe("2 m");
        expect(formatMeters(232, "metric")).toBe("230 m");
        expect(formatMeters(237, "metric")).toBe("240 m");
        expect(formatMeters(730, "metric")).toBe("700 m");
        expect(formatMeters(850, "metric")).toBe("900 m");
        expect(formatMeters(949, "metric")).toBe("900 m");
        expect(formatMeters(950, "metric")).toBe("1 km");
        expect(formatMeters(999, "metric")).toBe("1 km");
        expect(formatMeters(1000, "metric")).toBe("1 km");
        expect(formatMeters(1024, "metric")).toBe("1 km");
        expect(formatMeters(1099, "metric")).toBe("1.1 km");
        expect(formatMeters(1100, "metric")).toBe("1.1 km");
        expect(formatMeters(1830, "metric")).toBe("1.8 km");
        expect(formatMeters(2850, "metric")).toBe("2.9 km");
        expect(formatMeters(283520, "metric")).toBe("284 km");
        expect(formatMeters(2830100, "metric")).toBe("2830 km");
        expect(formatMeters(2, "imperial_us")).toBe("7 ft");
        expect(formatMeters(100, "imperial_us")).toBe("330 ft");
        expect(formatMeters(151.87, "imperial_us")).toBe("500 ft");
        expect(formatMeters(168.64, "imperial_us")).toBe("600 ft");
        expect(formatMeters(182.88, "imperial_us")).toBe("600 ft");
        expect(formatMeters(205.95, "imperial_us")).toBe("¼ mi");
        expect(formatMeters(800.95, "imperial_us")).toBe("½ mi");
        expect(formatMeters(1205.95, "imperial_us")).toBe("¾ mi");
        expect(formatMeters(1700, "imperial_us")).toBe("1 mi");
        expect(formatMeters(1855.95, "imperial_us")).toBe("1¼ mi");
        expect(formatMeters(2413.5, "imperial_us")).toBe("1½ mi");
        expect(formatMeters(4344.3, "imperial_us")).toBe("2¾ mi");
        expect(formatMeters(4633.92, "imperial_us")).toBe("3 mi");
        expect(formatMeters(4987.9, "imperial_us")).toBe("3 mi");
        expect(formatMeters(5309.7, "imperial_us")).toBe("3½ mi");
        expect(formatMeters(9332.2, "imperial_us")).toBe("6 mi");
        expect(formatMeters(18181.7, "imperial_us")).toBe("11 mi");
        expect(formatMeters(21753.68, "imperial_us")).toBe("14 mi");
        expect(formatMeters(2, "imperial_uk")).toBe("2 yd");
        expect(formatMeters(150.88, "imperial_uk")).toBe("170 yd");
        expect(formatMeters(205.95, "imperial_uk")).toBe("¼ mi");
        expect(formatMeters(2413.5, "imperial_uk")).toBe("1½ mi");
        expect(formatMeters(4344.3, "imperial_uk")).toBe("2¾ mi");
        expect(formatMeters(4633.92, "imperial_uk")).toBe("3 mi");
        expect(formatMeters(4987.9, "imperial_uk")).toBe("3 mi");
        expect(formatMeters(5309.7, "imperial_uk")).toBe("3½ mi");
        expect(formatMeters(9332.2, "imperial_uk")).toBe("6 mi");
        expect(formatMeters(18181.7, "imperial_uk")).toBe("11 mi");
        expect(formatMeters(21753.68, "imperial_uk")).toBe("14 mi");

        expect(formatMeters(-2, "metric")).toBe("-2 m");
        expect(formatMeters(-232, "metric")).toBe("-230 m");
        expect(formatMeters(-237, "metric")).toBe("-240 m");
        expect(formatMeters(-730, "metric")).toBe("-700 m");
        expect(formatMeters(-850, "metric")).toBe("-800 m");
        expect(formatMeters(-949, "metric")).toBe("-900 m");
        expect(formatMeters(-950, "metric")).toBe("-900 m");
        expect(formatMeters(-999, "metric")).toBe("-1 km");
        expect(formatMeters(-1000, "metric")).toBe("-1 km");
        expect(formatMeters(-1024, "metric")).toBe("-1 km");
        expect(formatMeters(-1099, "metric")).toBe("-1.1 km");
        expect(formatMeters(-1100, "metric")).toBe("-1.1 km");
        expect(formatMeters(-1830, "metric")).toBe("-1.8 km");
        expect(formatMeters(-2850, "metric")).toBe("-2.8 km");
        expect(formatMeters(-283520, "metric")).toBe("-284 km");
        expect(formatMeters(-2830100, "metric")).toBe("-2830 km");
        expect(formatMeters(-2, "imperial_us")).toBe("-7 ft");
        expect(formatMeters(-100, "imperial_us")).toBe("-330 ft");
        expect(formatMeters(-151.87, "imperial_us")).toBe("-500 ft");
        expect(formatMeters(-168.64, "imperial_us")).toBe("-600 ft");
        expect(formatMeters(-182.88, "imperial_us")).toBe("-600 ft");
        expect(formatMeters(-205.95, "imperial_us")).toBe("-¼ mi");
        expect(formatMeters(-805.95, "imperial_us")).toBe("-½ mi");
        expect(formatMeters(-1205.95, "imperial_us")).toBe("-¾ mi");
        expect(formatMeters(-1700, "imperial_us")).toBe("-1 mi");
        expect(formatMeters(-2413.5, "imperial_us")).toBe("-1½ mi");
        expect(formatMeters(-4344.3, "imperial_us")).toBe("-2¾ mi");
        expect(formatMeters(-4633.92, "imperial_us")).toBe("-3 mi");
        expect(formatMeters(-4987.9, "imperial_us")).toBe("-3 mi");
        expect(formatMeters(-5309.7, "imperial_us")).toBe("-3½ mi");
        expect(formatMeters(-9332.2, "imperial_us")).toBe("-6 mi");
        expect(formatMeters(-18181.7, "imperial_us")).toBe("-11 mi");
        expect(formatMeters(-21753.68, "imperial_us")).toBe("-14 mi");
        expect(formatMeters(-2, "imperial_uk")).toBe("-2 yd");
        expect(formatMeters(-150.88, "imperial_uk")).toBe("-160 yd");
        expect(formatMeters(-205.95, "imperial_uk")).toBe("-¼ mi");
        expect(formatMeters(-2413.5, "imperial_uk")).toBe("-1½ mi");
        expect(formatMeters(-4344.3, "imperial_uk")).toBe("-2¾ mi");
        expect(formatMeters(-4633.92, "imperial_uk")).toBe("-3 mi");
        expect(formatMeters(-4987.9, "imperial_uk")).toBe("-3 mi");
        expect(formatMeters(-5309.7, "imperial_uk")).toBe("-3½ mi");
        expect(formatMeters(-9332.2, "imperial_uk")).toBe("-6 mi");
        expect(formatMeters(-18181.7, "imperial_uk")).toBe("-11 mi");
        expect(formatMeters(-21753.68, "imperial_uk")).toBe("-14 mi");
    });
});
