/**
 * @module map-agent-tools
 */

import { sectionTypes } from '@tomtom-org/maps-sdk/core';
import type { Tool } from 'ai';
import type { ToolState } from '../types';
import { extractParametersFromSchema } from './extract-schema-params';
import {
    createFlyToTool,
    createGetMapStyleLayersTool,
    createGetViewportTool,
    createSetLayoutPropertiesTool,
    createSetPaintPropertiesTool,
    createSetPitchBearingTool,
    createZoomInOrOutTool,
    flyToDescription,
    flyToSchema,
    getMapStyleLayersDescription,
    getMapStyleLayersSchema,
    getViewportDescription,
    getViewportSchema,
    setLayoutPropertiesDescription,
    setLayoutPropertiesSchema,
    setPaintPropertiesDescription,
    setPaintPropertiesSchema,
    setPitchBearingDescription,
    setPitchBearingSchema,
    zoomInOrOutDescription,
    zoomInOrOutSchema,
} from './maplibre';
import {
    addStopToRouteDescription,
    addStopToRouteSchema,
    createAddStopToRouteTool,
    createDiscoverPlacesTool,
    createFindReachableAreaTool,
    createGetPoiCategoryCodesTool,
    createGetTrafficIncidentsTool,
    createLocatePlaceTool,
    createRemoveStopFromRouteTool,
    createReverseGeocodeTool,
    createSearchAlongRouteTool,
    createSetRouteLocationsTool,
    createSetRouteParametersTool,
    discoverPlacesDescription,
    discoverPlacesSchema,
    findReachableAreaDescription,
    findReachableAreaSchema,
    getPoiCategoryCodesDescription,
    getPoiCategoryCodesSchema,
    getTrafficIncidentsDescription,
    getTrafficIncidentsSchema,
    locatePlaceDescription,
    locatePlaceSchema,
    removeStopFromRouteDescription,
    removeStopFromRouteSchema,
    reverseGeocodeDescription,
    reverseGeocodeSchema,
    searchAlongRouteDescription,
    searchAlongRouteSchema,
    setRouteLocationsDescription,
    setRouteLocationsSchema,
    setRouteParametersDescription,
    setRouteParametersSchema,
} from './services';
import {
    clearMapDescription,
    clearMapSchema,
    createClearMapTool,
    createFitRouteSectionTool,
    createGetCurrentWaypointsTool,
    createGetShownIncidentsTool,
    createGetShownPlacesTool,
    createGetShownRouteSectionsTool,
    createGetShownRoutesTool,
    createGetShownRouteTrafficIncidentsTool,
    createGetShownWaypointsTool,
    createGetStandardMapStylesTool,
    createRecallPlacesTool,
    createRecallRangesTool,
    createRecallRoutesTool,
    createSetLanguageTool,
    createSetMapStandardStyleTool,
    createSetRouteThemeTool,
    createShowPlacesTool,
    createShowRoutesTool,
    createShowWaypointsTool,
    createToggleBaseMapLayerGroupsTool,
    createTogglePOIsTool,
    createToggleTrafficFlowTool,
    createToggleTrafficIncidentsTool,
    fitRouteSectionDescription,
    fitRouteSectionSchema,
    getCurrentWaypointsDescription,
    getCurrentWaypointsSchema,
    getShownIncidentsDescription,
    getShownIncidentsSchema,
    getShownPlacesDescription,
    getShownPlacesSchema,
    getShownRouteSectionsDescription,
    getShownRouteSectionsSchema,
    getShownRoutesDescription,
    getShownRoutesSchema,
    getShownRouteTrafficIncidentsDescription,
    getShownRouteTrafficIncidentsSchema,
    getShownWaypointsDescription,
    getShownWaypointsSchema,
    getStandardMapStylesDescription,
    getStandardMapStylesSchema,
    recallPlacesDescription,
    recallPlacesSchema,
    recallRangesDescription,
    recallRangesSchema,
    recallRoutesDescription,
    recallRoutesSchema,
    setLanguageDescription,
    setLanguageSchema,
    setMapStandardStyleDescription,
    setMapStandardStyleSchema,
    setRouteThemeDescription,
    setRouteThemeSchema,
    showPlacesDescription,
    showPlacesSchema,
    showRouteDescription,
    showRouteSchema,
    showWaypointsDescription,
    showWaypointsSchema,
    toggleBaseMapLayerGroupsDescription,
    toggleBaseMapLayerGroupsSchema,
    togglePOIsDescription,
    togglePOIsSchema,
    toggleTrafficFlowDescription,
    toggleTrafficFlowSchema,
    toggleTrafficIncidentsDescription,
    toggleTrafficIncidentsSchema,
} from './tomtom-map';
import { type ToolTag } from './tool-tags';
import {
    calculateBBoxDescription,
    calculateBBoxSchema,
    createCalculateBBoxTool,
    createFormatDistanceTool,
    createFormatDurationTool,
    createGetCurrentLocationTool,
    createGetRouteProgressTool,
    createGetSectionBBoxTool,
    createGetSectionProgressTool,
    createHelpTool,
    formatDistanceDescription,
    formatDistanceSchema,
    formatDurationDescription,
    formatDurationSchema,
    getCurrentLocationDescription,
    getCurrentLocationSchema,
    getRouteProgressDescription,
    getRouteProgressSchema,
    getSectionBBoxDescription,
    getSectionBBoxSchema,
    getSectionProgressDescription,
    getSectionProgressSchema,
    helpDescription,
    helpSchema,
} from './utilities';

/**
 * Metadata for a single tool in the registry.
 */
export type ToolMetadata = {
    name: ToolName;
    description: string;
    /** Compact one-liner. */
    shortDescription: string;
    tags: ToolTag[];
    parameters: Array<{
        name: string;
        type: string;
        required: boolean;
        description: string;
    }>;
    examples: string[];
    examplePrompts: string[];
    relatedTools?: ToolName[];
    /** Tools whose output this tool directly consumes as input. */
    dependsOn?: ToolName[];
    /** Factory function to create the tool instance */
    create: (state: ToolState) => Tool;
};

/**
 * All valid tool names. Single source of truth — {@link ToolName} and {@link TOOL_REGISTRY}
 * keys are both derived from this array, and it can be reused for Zod enum schemas.
 */
export const TOOL_NAMES = [
    'addStopToRoute',
    'calculateBBox',
    'setRouteLocations',
    'setRouteParameters',
    'clearMap',
    'flyTo',
    'fitRouteSection',
    'formatDistance',
    'formatDuration',
    'getCurrentWaypoints',
    'getCurrentLocation',
    'getMapStyleLayers',
    'getPOICategoryCodes',
    'recallPlaces',
    'getRouteProgress',
    'recallRoutes',
    'getSectionBBox',
    'getSectionProgress',
    'getShownIncidents',
    'getShownPlaces',
    'getShownRouteTrafficIncidents',
    'getShownRouteSections',
    'getShownRoutes',
    'getShownWaypoints',
    'getStandardMapStyles',
    'getTrafficIncidents',
    'getViewport',
    'help',
    'removeStopFromRoute',
    'locatePlace',
    'reverseGeocode',
    'discoverPlaces',
    'setLanguage',
    'setLayoutProperties',
    'setMapStandardStyle',
    'setRouteTheme',
    'setPaintProperties',
    'setPitchBearing',
    'zoomInOrOut',
    'showPlaces',
    'showRoute',
    'showWaypoints',
    'toggleBaseMapLayerGroups',
    'togglePOIs',
    'toggleTrafficFlow',
    'toggleTrafficIncidents',
    'findReachableArea',
    'searchAlongRoute',
    'recallRanges',
] as const;

/** Union of all valid tool names, derived from {@link TOOL_NAMES}. */
export type ToolName = (typeof TOOL_NAMES)[number];

/**
 * Complete tool registry with metadata and factory functions for all available tools.
 */
export const TOOL_REGISTRY: Record<ToolName, ToolMetadata> = {
    locatePlace: {
        name: 'locatePlace',
        description: locatePlaceDescription,
        shortDescription:
            'Resolve a single location string (landmark, city, address) to a place without showing it; optionally stages a waypoint slot.',
        tags: ['locate', 'place', 'location', 'waypoint'],
        parameters: extractParametersFromSchema(locatePlaceSchema),
        examples: [
            'locatePlace("Buckingham Palace", where: "within-map-bounds", waypointIndex: 0)',
            'locatePlace("Tower Bridge", where: "nearby-map-center", waypointIndex: 1)',
            'locatePlace("Westminster Abbey", where: "anywhere")',
            'locatePlace("Central Station", where: { position: [4.9, 52.37] })',
        ],
        examplePrompts: ['Where is the Louvre?', 'Find the nearest train station', 'Locate Big Ben'],
        relatedTools: ['setRouteLocations', 'addStopToRoute', 'getCurrentWaypoints', 'recallPlaces'],
        create: createLocatePlaceTool,
    },
    reverseGeocode: {
        name: 'reverseGeocode',
        description: reverseGeocodeDescription,
        shortDescription:
            'Convert [lng, lat] coordinates to an address; use after map clicks or any tool that returns a position.',
        tags: ['location', 'place'],
        parameters: extractParametersFromSchema(reverseGeocodeSchema),
        examples: ['reverseGeocode({ position: [4.9, 52.4] })'],
        examplePrompts: ["What's the address at this point?", 'What street is at these coordinates?'],
        relatedTools: ['getViewport', 'getCurrentLocation', 'showPlaces', 'locatePlace'],
        create: createReverseGeocodeTool,
    },
    discoverPlaces: {
        name: 'discoverPlaces',
        description: discoverPlacesDescription,
        shortDescription:
            'Search for multiple places by text query or POI category within an area; call showPlaces to display results.',
        tags: ['discover', 'place', 'location'],
        parameters: extractParametersFromSchema(discoverPlacesSchema),
        examples: [
            'discoverPlaces(query: "coffee", position: [4.9, 52.4])',
            'discoverPlaces(poiCategories: ["ITALIAN_RESTAURANT"])  // category-only, no query needed',
            'discoverPlaces(query: "hotel", boundingBox: [4.8, 52.3, 5.0, 52.5])',
            'discoverPlaces(query: "parking", boundingBox: geoJsonFeature)',
            'discoverPlaces({ query: "coffee", withinRange: "ranges-0" })',
        ],
        examplePrompts: [
            'Find coffee shops near me',
            'Search for Italian restaurants in Amsterdam',
            'Show me parking nearby',
            'Find coffee shops within the range I just calculated',
        ],
        relatedTools: ['getPOICategoryCodes', 'showPlaces', 'locatePlace', 'getViewport', 'findReachableArea'],
        create: createDiscoverPlacesTool,
    },
    setRouteLocations: {
        name: 'setRouteLocations',
        description: setRouteLocationsDescription,
        shortDescription:
            'Set route waypoints by resolving location queries and trigger a recalculation (minimum: origin + destination).',
        tags: ['route', 'waypoint', 'location'],
        parameters: extractParametersFromSchema(setRouteLocationsSchema),
        examples: [
            'setRouteLocations({ locations: [{ query: "Amsterdam" }, { query: "Brussels" }] })',
            'setRouteLocations({ locations: [{ query: "Eiffel Tower" }, { query: "Louvre Museum" }, { query: "Notre Dame" }] })',
            'setRouteLocations({ locations: [{ query: "5th Ave, New York", locationType: "default" }, { query: "JFK Airport", locationType: "default" }] })',
        ],
        examplePrompts: [
            'Get directions from Paris to Lyon',
            'Route me from Amsterdam to Brussels',
            'Navigate from here to the airport',
        ],
        relatedTools: ['setRouteParameters', 'showRoute', 'addStopToRoute', 'removeStopFromRoute'],
        create: createSetRouteLocationsTool,
    },
    setRouteParameters: {
        name: 'setRouteParameters',
        description: setRouteParametersDescription,
        shortDescription:
            'Configure route options (alternatives, type, avoidances, departure/arrival time) and trigger recalculation if locations are set.',
        tags: ['route'],
        parameters: extractParametersFromSchema(setRouteParametersSchema),
        examples: [
            'setRouteParameters({ maxAlternatives: 2 })',
            'setRouteParameters({ costModel: { routeType: "fast", avoid: ["tollRoads"] } })',
            'setRouteParameters({ when: { option: "departAt", date: "2025-06-01T09:00:00Z" } })',
        ],
        examplePrompts: ['Avoid toll roads', 'Find the fastest route', 'Show 2 alternative routes', 'Depart at 9am'],
        relatedTools: ['setRouteLocations', 'showRoute'],
        create: createSetRouteParametersTool,
    },
    addStopToRoute: {
        name: 'addStopToRoute',
        description: addStopToRouteDescription,
        shortDescription: 'Insert a stop at the optimal position in the current route and recalculate.',
        tags: ['route', 'waypoint'],
        parameters: extractParametersFromSchema(addStopToRouteSchema),
        examples: [
            'addStopToRoute(location: "Westminster Abbey")',
            'addStopToRoute(location: "gas station near route")',
            'addStopToRoute()  // use the most recently resolved or shown place',
        ],
        examplePrompts: ['Add a stop at Westminster Abbey', 'Add a coffee break to my route'],
        relatedTools: ['locatePlace', 'setRouteLocations', 'showRoute', 'removeStopFromRoute'],
        dependsOn: ['setRouteLocations'],
        create: createAddStopToRouteTool,
    },
    removeStopFromRoute: {
        name: 'removeStopFromRoute',
        description: removeStopFromRouteDescription,
        shortDescription: 'Remove a stop by index from the current route and recalculate.',
        tags: ['route', 'waypoint'],
        parameters: extractParametersFromSchema(removeStopFromRouteSchema),
        examples: ['removeStopFromRoute(1)', 'removeStopFromRoute(2, 1)'],
        examplePrompts: ['Remove the second stop from my route', 'Delete the Utrecht stop'],
        relatedTools: ['addStopToRoute', 'setRouteLocations', 'showRoute'],
        dependsOn: ['setRouteLocations'],
        create: createRemoveStopFromRouteTool,
    },
    getPOICategoryCodes: {
        name: 'getPOICategoryCodes',
        description: getPoiCategoryCodesDescription,
        shortDescription:
            'Resolve natural-language category names (e.g. "gym", "italian food") to POICategory codes for discoverPlaces.',
        tags: ['discover', 'place'],
        parameters: extractParametersFromSchema(getPoiCategoryCodesSchema),
        examples: [
            'getPOICategoryCodes()',
            'getPOICategoryCodes(filters: ["gym"])',
            'getPOICategoryCodes(filters: ["italian restaurant"])  // multi-word phrase, spaces removed before matching',
            'getPOICategoryCodes(filters: ["restaurant"], language: "fr-FR")',
        ],
        examplePrompts: ['What POI categories are available?', "What's the code for gym?"],
        relatedTools: ['discoverPlaces', 'togglePOIs'],
        create: createGetPoiCategoryCodesTool,
    },
    getTrafficIncidents: {
        name: 'getTrafficIncidents',
        description: getTrafficIncidentsDescription,
        shortDescription:
            'Fetch traffic incidents by bbox or IDs without showing them; returns category, severity, and delay details.',
        tags: ['traffic', 'location'],
        parameters: extractParametersFromSchema(getTrafficIncidentsSchema),
        examples: [
            'getTrafficIncidents({ bbox: [4.728, 52.278, 5.080, 52.479] })',
            'getTrafficIncidents({ ids: ["incident-id-1", "incident-id-2"] })',
            'getTrafficIncidents({ bbox: [...], categoryFilter: ["accident", "jam"] })',
            'getTrafficIncidents({ bbox: [...], categoryFilter: ["roadworks"], timeValidityFilter: ["future"] })',
        ],
        examplePrompts: ['Fetch traffic incidents in Amsterdam', 'Any accidents in this area?'],
        relatedTools: ['getShownIncidents', 'toggleTrafficIncidents', 'calculateBBox', 'getViewport'],
        create: createGetTrafficIncidentsTool,
    },
    showPlaces: {
        name: 'showPlaces',
        description: showPlacesDescription,
        shortDescription: 'Display the most recent discoverPlaces/locatePlace results as markers on the map.',
        tags: ['place', 'location'],
        parameters: extractParametersFromSchema(showPlacesSchema),
        examples: ['showPlaces()', 'showPlaces(false)'],
        examplePrompts: ['Show the results on the map', 'Pin the search results', 'Display these places'],
        relatedTools: ['discoverPlaces', 'locatePlace', 'reverseGeocode', 'clearMap', 'flyTo'],
        dependsOn: ['discoverPlaces', 'locatePlace'],
        create: createShowPlacesTool,
    },
    showRoute: {
        name: 'showRoute',
        description: showRouteDescription,
        shortDescription: 'Render the most recently calculated route on the map and fit the camera to it.',
        tags: ['route', 'waypoint'],
        parameters: extractParametersFromSchema(showRouteSchema),
        examples: ['showRoute()', 'showRoute({ selectedIndex: 1 })', 'showRoute({ fitBounds: false })'],
        examplePrompts: ['Draw the route on the map', 'Show the directions', 'Display the calculated route'],
        relatedTools: ['setRouteLocations', 'getShownRouteSections', 'clearMap'],
        dependsOn: ['setRouteLocations'],
        create: createShowRoutesTool,
    },
    showWaypoints: {
        name: 'showWaypoints',
        description: showWaypointsDescription,
        shortDescription: 'Display staged origin/stop/destination markers without drawing the route line.',
        tags: ['waypoint', 'route'],
        parameters: extractParametersFromSchema(showWaypointsSchema),
        examples: ['showWaypoints()'],
        examplePrompts: ['Show the waypoints on the map', 'Mark my route stops'],
        relatedTools: ['setRouteLocations', 'showRoute', 'getShownWaypoints', 'clearMap'],
        dependsOn: ['setRouteLocations', 'locatePlace'],
        create: createShowWaypointsTool,
    },
    getShownPlaces: {
        name: 'getShownPlaces',
        description: getShownPlacesDescription,
        shortDescription: 'Return places currently displayed on the map (available after showPlaces or locatePlace).',
        tags: ['place', 'location'],
        parameters: extractParametersFromSchema(getShownPlacesSchema),
        examples: ['getShownPlaces()'],
        examplePrompts: ['What places are on the map?', 'List the pinned locations'],
        relatedTools: ['showPlaces', 'clearMap', 'locatePlace', 'reverseGeocode'],
        dependsOn: ['showPlaces'],
        create: createGetShownPlacesTool,
    },
    getShownRoutes: {
        name: 'getShownRoutes',
        description: getShownRoutesDescription,
        shortDescription: 'Return routes currently rendered on the map (available after showRoute).',
        tags: ['route'],
        parameters: extractParametersFromSchema(getShownRoutesSchema),
        examples: ['getShownRoutes()'],
        examplePrompts: ['What routes are displayed?', 'Is there a route on the map?'],
        relatedTools: ['showRoute', 'clearMap'],
        dependsOn: ['showRoute'],
        create: createGetShownRoutesTool,
    },
    getShownWaypoints: {
        name: 'getShownWaypoints',
        description: getShownWaypointsDescription,
        shortDescription:
            'Return waypoint markers currently shown on the map (available after showRoute or showWaypoints).',
        tags: ['waypoint', 'route'],
        parameters: extractParametersFromSchema(getShownWaypointsSchema),
        examples: ['getShownWaypoints()'],
        examplePrompts: ['What waypoints are shown?', 'List the stops on the map'],
        relatedTools: ['showRoute', 'clearMap'],
        dependsOn: ['showRoute', 'showWaypoints'],
        create: createGetShownWaypointsTool,
    },
    getShownRouteTrafficIncidents: {
        name: 'getShownRouteTrafficIncidents',
        description: getShownRouteTrafficIncidentsDescription,
        shortDescription: 'Return traffic incidents overlaid on the shown route.',
        tags: ['traffic', 'route'],
        parameters: extractParametersFromSchema(getShownRouteTrafficIncidentsSchema),
        examples: ['getShownRouteTrafficIncidents()'],
        examplePrompts: ['What traffic incidents are on my route?', 'Any delays along the route?'],
        relatedTools: ['showRoute', 'clearMap', 'setRouteLocations'],
        dependsOn: ['showRoute'],
        create: createGetShownRouteTrafficIncidentsTool,
    },
    getShownRouteSections: {
        name: 'getShownRouteSections',
        description: getShownRouteSectionsDescription,
        shortDescription: 'Return sections of a given type (toll, country, motorway, traffic) from the shown route.',
        tags: ['route', 'location', ...sectionTypes],
        parameters: extractParametersFromSchema(getShownRouteSectionsSchema),
        examples: [
            'getShownRouteSections("toll")',
            'getShownRouteSections("country")',
            'getShownRouteSections("traffic")',
            'getShownRouteSections("motorway")',
        ],
        examplePrompts: [
            'What countries does the route pass through?',
            'Show me the toll sections',
            'List the motorway sections on my route',
        ],
        relatedTools: ['showRoute', 'getShownRoutes', 'getShownRouteTrafficIncidents', 'fitRouteSection'],
        dependsOn: ['showRoute'],
        create: createGetShownRouteSectionsTool,
    },
    getShownIncidents: {
        name: 'getShownIncidents',
        description: getShownIncidentsDescription,
        shortDescription:
            'Return real-time incidents currently visible in the map viewport (rendered on map, not fetched from service).',
        tags: ['traffic', 'location'],
        parameters: extractParametersFromSchema(getShownIncidentsSchema),
        examples: ['getShownIncidents()'],
        examplePrompts: ['What traffic incidents are visible?', 'Any incidents in the current view?'],
        relatedTools: ['toggleTrafficIncidents', 'flyTo', 'getViewport'],
        dependsOn: ['toggleTrafficIncidents'],
        create: createGetShownIncidentsTool,
    },
    clearMap: {
        name: 'clearMap',
        description: clearMapDescription,
        shortDescription: 'Remove displayed places, routes, or all features from the map.',
        tags: ['place', 'route', 'map style'],
        parameters: extractParametersFromSchema(clearMapSchema),
        examples: ['clearMap()', 'clearMap(["places"])', 'clearMap(["places", "routes"])'],
        examplePrompts: ['Clear the map', 'Remove all markers', 'Start fresh'],
        relatedTools: ['showPlaces', 'showRoute'],
        create: createClearMapTool,
    },
    flyTo: {
        name: 'flyTo',
        description: flyToDescription,
        shortDescription:
            'Move the camera to a bounding box or specific position; use after locating places or computing bounds.',
        tags: ['location', 'map style'],
        parameters: extractParametersFromSchema(flyToSchema),
        examples: [
            'flyTo({ where: { boundingBox: [4.8, 52.3, 5.0, 52.5] } })',
            'flyTo({ where: { boundingBox: [4.8, 52.3, 5.0, 52.5], padding: 100 } })',
            'flyTo({ where: { position: [4.9, 52.4], zoom: 14 } })',
        ],
        examplePrompts: ['Go to Berlin', 'Center the map on Rome', 'Fly to these coordinates'],
        relatedTools: ['getViewport', 'locatePlace', 'showPlaces', 'showRoute', 'calculateBBox'],
        create: createFlyToTool,
    },
    fitRouteSection: {
        name: 'fitRouteSection',
        description: fitRouteSectionDescription,
        shortDescription:
            'Fit the camera to a specific route section by type and ID; use getShownRouteSections for valid IDs.',
        tags: ['route', 'map style', ...sectionTypes],
        parameters: extractParametersFromSchema(fitRouteSectionSchema),
        examples: ['fitRouteSection("country", "NLD-section-1")', 'fitRouteSection("traffic", "traffic-1", 100)'],
        examplePrompts: ['Zoom to the toll section', 'Fit the Netherlands part of the route in view'],
        relatedTools: ['flyTo', 'showRoute', 'getShownRoutes', 'getShownRouteTrafficIncidents'],
        dependsOn: ['getShownRouteSections'],
        create: createFitRouteSectionTool,
    },
    getViewport: {
        name: 'getViewport',
        description: getViewportDescription,
        shortDescription:
            'Return the map center, zoom, and bounding box; use for area-relative queries like "in this area" or "near the map center".',
        tags: ['location', 'map style'],
        parameters: extractParametersFromSchema(getViewportSchema),
        examples: ['getViewport()'],
        examplePrompts: [
            'Where is the map centered?',
            "What's the current map area?",
            'What are the current map bounds?',
        ],
        relatedTools: ['locatePlace', 'flyTo', 'discoverPlaces', 'reverseGeocode', 'getTrafficIncidents'],
        create: createGetViewportTool,
    },
    recallPlaces: {
        name: 'recallPlaces',
        description: recallPlacesDescription,
        shortDescription: 'Return the history of locatePlace/discoverPlaces calls made in this session.',
        tags: ['place', 'location'],
        parameters: extractParametersFromSchema(recallPlacesSchema),
        examples: ['recallPlaces()', 'recallPlaces({ id: "places-0" })'],
        examplePrompts: [
            'What places did I search for?',
            'Show the coffee shops from earlier',
            'What was the first place we looked up?',
        ],
        relatedTools: ['discoverPlaces', 'locatePlace', 'reverseGeocode', 'showPlaces'],
        dependsOn: ['locatePlace', 'discoverPlaces'],
        create: createRecallPlacesTool,
    },
    recallRoutes: {
        name: 'recallRoutes',
        description: recallRoutesDescription,
        shortDescription: 'Return previously calculated routes from this session.',
        tags: ['route'],
        parameters: extractParametersFromSchema(recallRoutesSchema),
        examples: ['recallRoutes()', 'recallRoutes({ id: "routes-0" })'],
        examplePrompts: [
            'What routes have I calculated?',
            'Show the first route we planned',
            'What was the route to Schiphol?',
        ],
        relatedTools: ['setRouteLocations', 'showRoute', 'getCurrentWaypoints'],
        dependsOn: ['setRouteLocations'],
        create: createRecallRoutesTool,
    },
    getCurrentWaypoints: {
        name: 'getCurrentWaypoints',
        description: getCurrentWaypointsDescription,
        shortDescription: 'Return the staged waypoint slots (origin, stops, destination) not yet committed to a route.',
        tags: ['waypoint', 'route'],
        parameters: extractParametersFromSchema(getCurrentWaypointsSchema),
        examples: [
            'getCurrentWaypoints()',
            'getCurrentWaypoints({ slotIndex: 1 })',
            'getCurrentWaypoints({ includeEmptySlots: true })',
            'getCurrentWaypoints({ offset: 2, limit: 4 })',
        ],
        examplePrompts: ['What are my current route waypoints?', "What's my destination?", 'Show my staged stops'],
        relatedTools: ['locatePlace', 'setRouteLocations', 'showWaypoints', 'recallRoutes'],
        create: createGetCurrentWaypointsTool,
    },
    getStandardMapStyles: {
        name: 'getStandardMapStyles',
        description: getStandardMapStylesDescription,
        shortDescription: 'List available standard map style IDs for use with setMapStandardStyle.',
        tags: ['map style'],
        parameters: extractParametersFromSchema(getStandardMapStylesSchema),
        examples: ['getStandardMapStyles()'],
        examplePrompts: ['What map styles are available?', 'List the map themes'],
        relatedTools: ['setMapStandardStyle'],
        create: createGetStandardMapStylesTool,
    },
    setMapStandardStyle: {
        name: 'setMapStandardStyle',
        description: setMapStandardStyleDescription,
        shortDescription: 'Switch the map to a standard style preset (light, dark, satellite, driving, etc.).',
        tags: ['map style'],
        parameters: extractParametersFromSchema(setMapStandardStyleSchema),
        examples: ['setMapStandardStyle("standardDark")', 'setMapStandardStyle("satellite")'],
        examplePrompts: ['Switch to dark mode', 'Use the satellite view', 'Change to the light theme'],
        relatedTools: ['getStandardMapStyles', 'setLanguage', 'toggleBaseMapLayerGroups', 'getMapStyleLayers'],
        create: createSetMapStandardStyleTool,
    },
    setRouteTheme: {
        name: 'setRouteTheme',
        description: setRouteThemeDescription,
        shortDescription: 'Color the route line and waypoint icons; prefer over setPaintProperties for route styling.',
        tags: ['route', 'map style'],
        parameters: extractParametersFromSchema(setRouteThemeSchema),
        examples: [
            'setRouteTheme({ mainColor: "#FF0000" })  // red route',
            'setRouteTheme({ mainColor: "coral" })',
            'setRouteTheme({ mainColor: "steelblue" })',
        ],
        examplePrompts: ['Make the route line red', 'Change the route color to blue', 'Style the route in coral'],
        relatedTools: ['showRoute', 'setRouteLocations', 'setPaintProperties'],
        dependsOn: ['showRoute'],
        create: createSetRouteThemeTool,
    },
    setLanguage: {
        name: 'setLanguage',
        description: setLanguageDescription,
        shortDescription: 'Change the language for map labels and all subsequent service API responses.',
        tags: ['map style'],
        parameters: extractParametersFromSchema(setLanguageSchema),
        examples: ['setLanguage("fr-FR")', 'setLanguage("de-DE")'],
        examplePrompts: ['Show map labels in French', 'Switch the map to German', 'Use Spanish for place names'],
        relatedTools: ['setMapStandardStyle'],
        create: createSetLanguageTool,
    },
    toggleBaseMapLayerGroups: {
        name: 'toggleBaseMapLayerGroups',
        description: toggleBaseMapLayerGroupsDescription,
        shortDescription:
            'Show or hide named base map layer groups (buildings3D, roadLabels, water, placeLabels, etc.).',
        tags: ['map style'],
        parameters: extractParametersFromSchema(toggleBaseMapLayerGroupsSchema),
        examples: [
            'toggleBaseMapLayerGroups(false, ["buildings3D"])',
            'toggleBaseMapLayerGroups(true, ["roadLabels"])',
        ],
        examplePrompts: ['Hide 3D buildings', 'Show road labels', 'Toggle the building layer'],
        relatedTools: ['togglePOIs', 'getMapStyleLayers', 'setMapStandardStyle'],
        create: createToggleBaseMapLayerGroupsTool,
    },
    togglePOIs: {
        name: 'togglePOIs',
        description: togglePOIsDescription,
        shortDescription: 'Show or hide built-in map POI icons with optional category filtering.',
        tags: ['place', 'map style'],
        parameters: extractParametersFromSchema(togglePOIsSchema),
        examples: [
            'togglePOIs({ allMapPOIsVisible: false })',
            'togglePOIs({ allMapPOIsVisible: true, filterCategories: { show: "only", values: ["RESTAURANT", "CAFE"] } })',
            'togglePOIs({ filterCategories: { show: "all_except", values: ["PARKING_GARAGE"] } })',
            'togglePOIs({ reset: true })',
        ],
        examplePrompts: ['Hide all POI icons', 'Show only restaurant POIs', 'Turn off parking icons'],
        relatedTools: ['toggleBaseMapLayerGroups', 'discoverPlaces', 'setMapStandardStyle'],
        create: createTogglePOIsTool,
    },
    toggleTrafficFlow: {
        name: 'toggleTrafficFlow',
        description: toggleTrafficFlowDescription,
        shortDescription: 'Show or hide the real-time traffic flow overlay (congestion color bands) on the map.',
        tags: ['traffic', 'map style'],
        parameters: extractParametersFromSchema(toggleTrafficFlowSchema),
        examples: ['toggleTrafficFlow(true)', 'toggleTrafficFlow(false)'],
        examplePrompts: ['Show traffic flow', 'Turn off traffic colors', 'Enable the congestion overlay'],
        relatedTools: ['toggleTrafficIncidents', 'setRouteLocations', 'getTrafficIncidents'],
        create: createToggleTrafficFlowTool,
    },
    toggleTrafficIncidents: {
        name: 'toggleTrafficIncidents',
        description: toggleTrafficIncidentsDescription,
        shortDescription:
            'Show or hide real-time traffic incident icons (accidents, jams, road closures, roadworks) on the map.',
        tags: ['traffic', 'map style'],
        parameters: extractParametersFromSchema(toggleTrafficIncidentsSchema),
        examples: ['toggleTrafficIncidents(true)', 'toggleTrafficIncidents(false)'],
        examplePrompts: ['Show traffic incidents', 'Hide accident icons', 'Enable incident markers'],
        relatedTools: ['toggleTrafficFlow', 'getTrafficIncidents', 'getShownIncidents', 'setRouteLocations'],
        create: createToggleTrafficIncidentsTool,
    },
    getMapStyleLayers: {
        name: 'getMapStyleLayers',
        description: getMapStyleLayersDescription,
        shortDescription: 'List MapLibre layer IDs with their paint/layout properties for custom styling.',
        tags: ['map style'],
        parameters: extractParametersFromSchema(getMapStyleLayersSchema),
        examples: ['getMapStyleLayers()', 'getMapStyleLayers("road")', 'getMapStyleLayers("water")'],
        examplePrompts: ['What are the paint properties of the water layer?', 'Show me the road layer layout'],
        relatedTools: ['setLayoutProperties', 'setPaintProperties'],
        create: createGetMapStyleLayersTool,
    },
    setLayoutProperties: {
        name: 'setLayoutProperties',
        description: setLayoutPropertiesDescription,
        shortDescription: 'Set MapLibre layout properties (visibility, text-field, icon-size) on named layers.',
        tags: ['map style'],
        parameters: extractParametersFromSchema(setLayoutPropertiesSchema),
        examples: [
            'setLayoutProperties([{ layerId: "road-label", propertyName: "visibility", value: "none" }])',
            'setLayoutProperties([{ layerId: "poi-label", propertyName: "text-field", value: "{name}" }, { layerId: "poi-label", propertyName: "icon-size", value: 1.2 }])',
        ],
        examplePrompts: [
            'Hide the road-label layer',
            'Change the text size on building labels',
            'Make the city labels bigger',
        ],
        relatedTools: ['getMapStyleLayers', 'setPaintProperties'],
        dependsOn: ['getMapStyleLayers'],
        create: createSetLayoutPropertiesTool,
    },
    setPaintProperties: {
        name: 'setPaintProperties',
        description: setPaintPropertiesDescription,
        shortDescription: 'Set MapLibre paint properties (colors, widths, opacity) on named layers.',
        tags: ['map style'],
        parameters: extractParametersFromSchema(setPaintPropertiesSchema),
        examples: [
            'setPaintProperties([{ layerId: "water", propertyName: "fill-color", value: "#0000ff" }])',
            'setPaintProperties([{ layerId: "road", propertyName: "line-color", value: "#ff0000" }, { layerId: "road", propertyName: "line-width", value: 3 }])',
        ],
        examplePrompts: [
            'Make the water bright blue',
            'Change the road color to red',
            'Make buildings semi-transparent',
            'Make the country borders pink',
        ],
        relatedTools: ['getMapStyleLayers', 'setLayoutProperties', 'setRouteTheme'],
        dependsOn: ['getMapStyleLayers'],
        create: createSetPaintPropertiesTool,
    },
    setPitchBearing: {
        name: 'setPitchBearing',
        description: setPitchBearingDescription,
        shortDescription: 'Tilt (pitch) and/or rotate (bearing) the map camera for a 3D perspective.',
        tags: ['map style'],
        parameters: extractParametersFromSchema(setPitchBearingSchema),
        examples: [
            'setPitchBearing({ pitch: 45 })',
            'setPitchBearing({ bearing: 90 })',
            'setPitchBearing({ pitch: 60, bearing: -45 })',
        ],
        examplePrompts: ['Tilt the map to 45 degrees', 'Rotate the map to face north', 'Set a 3D perspective view'],
        relatedTools: ['getViewport', 'locatePlace', 'flyTo'],
        create: createSetPitchBearingTool,
    },
    zoomInOrOut: {
        name: 'zoomInOrOut',
        description: zoomInOrOutDescription,
        shortDescription: 'Adjust the map zoom level by a delta; positive zooms in, negative zooms out.',
        tags: ['map style'],
        parameters: extractParametersFromSchema(zoomInOrOutSchema),
        examples: ['zoomInOrOut({ delta: 2 })', 'zoomInOrOut({ delta: -1 })'],
        examplePrompts: ['Zoom in', 'Zoom out 2 levels', 'Get a wider view'],
        relatedTools: ['getViewport', 'flyTo'],
        create: createZoomInOrOutTool,
    },
    calculateBBox: {
        name: 'calculateBBox',
        description: calculateBBoxDescription,
        shortDescription:
            'Compute a [minLng, minLat, maxLng, maxLat] bounding box from GeoJSON features or tool results.',
        tags: ['utilities', 'location'],
        parameters: extractParametersFromSchema(calculateBBoxSchema),
        examples: ['calculateBBox(place)', 'calculateBBox(routes)', 'calculateBBox([place1, place2])'],
        examplePrompts: ["What's the bounding box of these places?", 'Calculate the extent of this route'],
        relatedTools: ['flyTo', 'getViewport', 'showPlaces', 'showRoute'],
        create: createCalculateBBoxTool,
    },
    formatDistance: {
        name: 'formatDistance',
        description: formatDistanceDescription,
        shortDescription:
            'Format meters into a human-readable string (e.g. "2.5 km"); use after tools that return distances.',
        tags: ['utilities', 'route'],
        parameters: extractParametersFromSchema(formatDistanceSchema),
        examples: ['formatDistance(2500)', 'formatDistance(5000, "imperial_us")'],
        examplePrompts: ['Format 5000 meters as a distance', 'Convert meters to a readable string'],
        relatedTools: ['formatDuration', 'setRouteLocations', 'getSectionProgress', 'getRouteProgress'],
        create: createFormatDistanceTool,
    },
    formatDuration: {
        name: 'formatDuration',
        description: formatDurationDescription,
        shortDescription:
            'Format seconds into a human-readable string (e.g. "1 h 30 min"); use after tools that return durations.',
        tags: ['utilities', 'route'],
        parameters: extractParametersFromSchema(formatDurationSchema),
        examples: ['formatDuration(3600)', 'formatDuration(9000)'],
        examplePrompts: ['Format 3600 seconds as a duration', 'Convert seconds to hours and minutes'],
        relatedTools: ['formatDistance', 'setRouteLocations', 'getSectionProgress', 'getRouteProgress'],
        create: createFormatDurationTool,
    },
    getSectionProgress: {
        name: 'getSectionProgress',
        description: getSectionProgressDescription,
        shortDescription: 'Return the distance and travel time for one or more sections of the shown route by type.',
        tags: ['utilities', 'route', ...sectionTypes],
        parameters: extractParametersFromSchema(getSectionProgressSchema),
        examples: [
            'getSectionProgress({ sectionType: "country" })  // all country sections',
            'getSectionProgress({ sectionType: "traffic", ids: ["incident-id-1"] })',
            'getSectionProgress({ sectionType: "toll", ids: ["toll-1", "toll-2"] })',
        ],
        examplePrompts: ['How far is the toll section?', 'Travel time through France on this route'],
        relatedTools: ['setRouteLocations', 'fitRouteSection', 'formatDistance', 'formatDuration'],
        dependsOn: ['showRoute'],
        create: createGetSectionProgressTool,
    },
    getSectionBBox: {
        name: 'getSectionBBox',
        description: getSectionBBoxDescription,
        shortDescription: 'Return the bounding box of a specific route section; use with flyTo to frame it.',
        tags: ['utilities', 'route', 'location', ...sectionTypes],
        parameters: extractParametersFromSchema(getSectionBBoxSchema),
        examples: [
            'getSectionBBox({ sectionType: "country", id: "NLD-section-1" })',
            'getSectionBBox({ sectionType: "traffic", id: "traffic-1" })',
            'getSectionBBox({ sectionType: "toll", id: "toll-2" })',
        ],
        examplePrompts: ['Get the extent of the Netherlands section', 'Bounding box of the traffic incident'],
        relatedTools: ['flyTo', 'fitRouteSection', 'getSectionProgress', 'getShownRouteSections'],
        dependsOn: ['getShownRouteSections'],
        create: createGetSectionBBoxTool,
    },
    getRouteProgress: {
        name: 'getRouteProgress',
        description: getRouteProgressDescription,
        shortDescription:
            'Return the position along the shown route at a given traveled time, distance, or clock time.',
        tags: ['utilities', 'route', 'location'],
        parameters: extractParametersFromSchema(getRouteProgressSchema),
        examples: [
            'getRouteProgress(traveledTimeInSeconds: 600)',
            'getRouteProgress(traveledDistanceInMeters: 5000)',
            'getRouteProgress(clockTime: "2025-06-01T09:30:00Z")',
            'getRouteProgress(traveledTimeInSeconds: 300, routeIndex: 1)',
        ],
        examplePrompts: ['Where am I after 10 minutes of travel?', 'Position at 5km into the route'],
        relatedTools: ['setRouteLocations', 'getSectionProgress', 'formatDistance', 'formatDuration'],
        dependsOn: ['showRoute'],
        create: createGetRouteProgressTool,
    },
    getCurrentLocation: {
        name: 'getCurrentLocation',
        description: getCurrentLocationDescription,
        shortDescription:
            'Get the user\'s physical GPS location from the browser; use for "near me" queries, not map center.',
        tags: ['utilities', 'location'],
        parameters: extractParametersFromSchema(getCurrentLocationSchema),
        examples: ['getCurrentLocation()'],
        examplePrompts: ['Where am I?', 'Get my GPS location', 'Use my current position'],
        relatedTools: ['discoverPlaces', 'reverseGeocode', 'locatePlace'],
        create: createGetCurrentLocationTool,
    },
    help: {
        name: 'help',
        description: helpDescription,
        shortDescription:
            'Return available capabilities in summary or searchable detail mode; call when the user asks what you can do.',
        tags: ['utilities'],
        parameters: extractParametersFromSchema(helpSchema),
        examples: [
            'help({ mode: "summary" })',
            'help({ mode: "detail", query: "traffic" })',
            'help({ mode: "detail", tag: "route" })',
            'help({ mode: "detail", query: "route", tag: "utilities" })',
        ],
        examplePrompts: ['What can you do?', 'Show me available tools', 'How do I search for places?'],
        create: createHelpTool,
    },
    searchAlongRoute: {
        name: 'searchAlongRoute',
        description: searchAlongRouteDescription,
        shortDescription: 'Search for POIs along a calculated route ranked by detour cost.',
        tags: ['search', 'route', 'place', 'detour', 'along-route'],
        parameters: extractParametersFromSchema(searchAlongRouteSchema),
        examples: [
            'searchAlongRoute({ maxDetourTimeSeconds: 300, query: "coffee" })',
            'searchAlongRoute({ maxDetourTimeSeconds: 600, poiCategories: ["ELECTRIC_VEHICLE_STATION"], sortBy: "detourOffset" })',
            'searchAlongRoute({ maxDetourTimeSeconds: 300, routeIndex: 0, show: { markerType: "pin", zoomMode: "auto" } })',
        ],
        examplePrompts: [
            'Find gas stations along my route',
            'Show me coffee shops within 5 minutes off the route',
            'Any EV chargers I can reach from this route?',
            'I need a coffee stop on the way to the airport',
            'Find me a restaurant somewhere between here and Paris',
        ],
        relatedTools: ['setRouteLocations', 'recallRoutes', 'showPlaces', 'recallPlaces'],
        dependsOn: ['setRouteLocations'],
        create: createSearchAlongRouteTool,
    },
    findReachableArea: {
        name: 'findReachableArea',
        description: findReachableAreaDescription,
        shortDescription: 'Calculate isochrone/isodistance polygons showing how far you can travel from a point.',
        tags: ['reachable-range', 'isochrone', 'range', 'EV', 'coverage'],
        parameters: extractParametersFromSchema(findReachableAreaSchema),
        examples: [
            'findReachableArea({ origin: { query: "Amsterdam", locationType: "default" }, budgets: [{ type: "timeMinutes", value: 30 }], showOnMap: true })',
            'findReachableArea({ origin: { position: { lng: 4.9, lat: 52.3 } }, budgets: [{ type: "timeMinutes", value: 10 }, { type: "timeMinutes", value: 30 }], showOnMap: true, theme: "inverted" })',
            'findReachableArea({ origin: { query: "my location", locationType: "default" }, budgets: [{ type: "distanceKM", value: 50 }], showOnMap: false })',
        ],
        examplePrompts: [
            'Show me where I can reach in 30 minutes from Amsterdam',
            'What area is within 50 km of Berlin?',
            'Show 10, 20, 30 minute drive zones from here',
        ],
        relatedTools: ['recallRanges', 'locatePlace'],
        create: createFindReachableAreaTool,
    },
    recallRanges: {
        name: 'recallRanges',
        description: recallRangesDescription,
        shortDescription: 'Retrieve stored reachable range results from session history.',
        tags: ['recall', 'reachable-range', 'state'],
        parameters: extractParametersFromSchema(recallRangesSchema),
        examples: ['recallRanges()', 'recallRanges({ id: "ranges-0" })'],
        examplePrompts: ['What range did I calculate earlier?', 'Recall the isochrone from Amsterdam'],
        relatedTools: ['findReachableArea'],
        create: createRecallRangesTool,
    },
};

/**
 * Get tool metadata by name.
 */
export function getToolMetadata(toolName: ToolName): ToolMetadata;
export function getToolMetadata(toolName: string): ToolMetadata | undefined {
    return TOOL_REGISTRY[toolName as ToolName];
}

/**
 * Create a tool instance from the registry.
 */
export function createToolFromRegistry(toolName: ToolName, state: ToolState): Tool;
export function createToolFromRegistry(toolName: string, state: ToolState): Tool | undefined {
    const metadata = TOOL_REGISTRY[toolName as ToolName];
    return metadata?.create(state);
}

/**
 * Create all tools from the registry.
 */
export function createAllToolsFromRegistry(state: ToolState): Record<ToolName, Tool> {
    const tools = {} as Record<ToolName, Tool>;
    for (const name in TOOL_REGISTRY) {
        tools[name as ToolName] = TOOL_REGISTRY[name as ToolName].create(state);
    }
    return tools;
}
