import type { POICategory } from '@anw/maps-sdk-js/core';

/**
 * @ignore
 */
const mapDisplayPOICategoryMappings: Partial<Record<POICategory, string>> = {
    ACCESS_GATEWAY: 'access_gateway',
    ADVENTURE_SPORTS_FACILITY: 'adventure_sports_facility',
    ADVENTURE_SPORTS_VENUE: 'adventure_sports_venue',
    AGRICULTURE: 'agriculture_business',
    AIRPORT: 'airport',
    AMUSEMENT_PARK: 'amusement_park',
    AQUATIC_ZOO: 'zoo_or_aquarium',
    ASHRAM: 'religious_site',
    ATM: 'atm',
    AUTOMOTIVE_DEALER: 'automotive_dealer',
    BANK: 'bank',
    BEACH: 'beach',
    BUS_STOP: 'bus_station',
    BUSINESS_PARK: 'business_park',
    CAFE_PUB: 'cafe',
    CAMPING_GROUND: 'camping_ground',
    CAR_WASH: 'car_wash',
    CASH_DISPENSER: 'atm',
    CASINO: 'casino',
    CLOTHING_SHOP: 'clothing_shop',
    CHURCH: 'religious_site',
    CINEMA: 'cinema',
    CLUB_ASSOCIATION: 'club_and_association',
    COLLEGE_UNIVERSITY: 'college_or_university',
    COMMERCIAL_BUILDING: 'commercial_building',
    COMMUNITY_CENTER: 'community_center',
    COMPANY: 'company_or_office',
    CONCERT_HALL: 'nightlife',
    COURTHOUSE: 'courthouse',
    CULTURAL_CENTER: 'cultural_center',
    DENTIST: 'dentist',
    DEPARTMENT_STORE: 'department_store',
    DOCTOR: 'doctor',
    ELECTRIC_VEHICLE_STATION: 'charging_location',
    EMBASSY: 'institution_office',
    EMERGENCY_MEDICAL_SERVICE: 'emergency_medical_service',
    EMERGENCY_ROOM: 'emergency_room',
    ENTERTAINMENT: 'entertainment',
    EXCHANGE: 'stock_exchange',
    EXHIBITION_CONVENTION_CENTER: 'cultural_center',
    FERRY_TERMINAL: 'ferry_terminal',
    FIRE_STATION_BRIGADE: 'fire_station',
    FRONTIER_CROSSING: 'frontier_crossing',
    FUEL_FACILITIES: 'fuel_station',
    GAS_STATION: 'fuel_station',
    GEOGRAPHIC_FEATURE: 'geographic_feature',
    GOLD_EXCHANGE: 'gold_exchange',
    GOLF_COURSE: 'golf_course',
    GOVERNMENT_OFFICE: 'institution_office',
    GURUDWARA: 'religious_site',
    HEALTH_CARE_SERVICE: 'healthcare_service',
    HELIPAD_HELICOPTER_LANDING: 'heliport_or_helipad',
    HILL: 'elevation_point',
    HOLIDAY_RENTAL: 'holiday_home',
    HOSPITAL: 'hospital',
    HOSPITAL_POLYCLINIC: 'hospital',
    HOTEL_MOTEL: 'hotel_or_motel',
    ICE_SKATING_RINK: 'ice_skating_rink',
    IMPORTANT_TOURIST_ATTRACTION: 'tourist_attraction',
    INDUSTRIAL_BUILDING: 'industrial_building',
    LEISURE_CENTER: 'leisure_center',
    LIBRARY: 'library',
    MANUFACTURING_FACILITY: 'manufacturing_facility',
    MARINA: 'marina',
    MARKET: 'marketplace',
    MEDIA_FACILITY: 'media_facility',
    MILITARY_INSTALLATION: 'military_facility',
    MOSQUE: 'religious_site',
    MOTORING_ORGANIZATION_OFFICE: 'motoring_organization_office',
    MOUNTAIN_PASS: 'mountain_pass',
    MOUNTAIN_PEAK: 'elevation_point',
    MOVIE_THEATER: 'cinema',
    MUSEUM: 'museum',
    NATIVE_RESERVATION: 'native_reservation',
    NIGHTLIFE: 'nightlife',
    NON_GOVERNMENTAL_ORGANIZATION: 'non_governmental_organization',
    OPEN_PARKING_AREA: 'parking_facility',
    OPERA_HOUSE: 'theater',
    PAGODA: 'religious_site',
    PARK_RECREATION_AREA: 'park_and_recreation_area',
    PARKING_GARAGE: 'parking_facility',
    PETROL_STATION: 'fuel_station',
    PHARMACY: 'pharmacy',
    PLACE_OF_WORSHIP: 'place_of_worship',
    POLICE_STATION: 'police_station',
    PORT_WAREHOUSE_FACILITY: 'port_or_warehouse_facility',
    POST_OFFICE: 'post_office',
    PRIMARY_RESOURCE_UTILITY: 'primary_resource_or_utility',
    PRISON_CORRECTIONAL_FACILITY: 'prison',
    PUBLIC_AMENITY: 'public_amenity',
    PUBLIC_TRANSPORT_STOP: 'public_transport_stop',
    RAILWAY_STATION: 'railway_station',
    RENT_A_CAR_FACILITY: 'car_rental',
    RENT_A_CAR_PARKING: 'rent_a_car_parking',
    REPAIR_FACILITY: 'repair_facility',
    RESEARCH_FACILITY: 'research_facility',
    RESIDENTIAL_ACCOMMODATION: 'urban_ground',
    REST_AREA: 'rest_area',
    RESTAURANT: 'restaurant',
    RESTAURANT_AREA: 'restaurant_area',
    SCENIC_PANORAMIC_VIEW: 'viewpoint',
    SCHOOL: 'school',
    SHOP: 'shop_or_store',
    SHOPPING_CENTER: 'shop_or_store',
    SPORTS_CENTER: 'sport_facility',
    STADIUM: 'stadium',
    SUPERMARKETS_HYPERMARKETS: 'supermarket',
    SWIMMING_POOL: 'swimming_pool',
    SYNAGOG: 'religious_site',
    TAXI_STAND: 'taxi_stand',
    TEMPLE: 'religious_site',
    TENNIS_COURT: 'tennis_court',
    THEATER: 'theater',
    TOLL_GATE: 'toll_gate',
    TOURIST_INFORMATION_OFFICE: 'tourist_information_office',
    TRAFFIC_CONTROL_DEPARTMENT: 'traffic_control_department',
    TRAFFIC_SERVICE_CENTER: 'traffic_service_center',
    TRAIL_SYSTEM: 'trail_system',
    TRAILS: 'trails',
    TRANSPORT_AUTHORITY_VEHICLE_REGISTRATION: 'transport_authority_or_vehicle_registration',
    TRUCK_STOP: 'truck_stop',
    VACATION_RENTAL: 'vacation_rental',
    VETERINARIAN: 'veterinarian',
    WATER_SPORT: 'water_sport',
    WEIGH_STATION: 'weigh_station',
    WELFARE_ORGANIZATION: 'welfare_organization',
    WINERY: 'manufacturing_facility',
    ZOOS_ARBORETA_BOTANICAL_GARDEN: 'zoo_or_aquarium',
};

export type MapStylePOICategory = keyof typeof mapDisplayPOICategoryMappings;

/**
 * @ignore
 */
export const toMapDisplayPOICategory = (category: POICategory): string =>
    // if it's one of the different categories between search and poi layer, use poi layer category
    category in mapDisplayPOICategoryMappings
        ? (mapDisplayPOICategoryMappings[category] as string)
        : category.toLowerCase();
