import { AxiosError } from "axios";
import {
    APIErrorCode,
    DefaultAPIResponseError,
    ErrorObjAPI,
    GeocodeAPIResponseError,
    RoutingAPIResponseError
} from "./types/APIResponseErrorTypes";

/**
 * Main Error Class for the whole SDK to help with error handling.
 *  SDK will have two different types of errors:
 *
 *  1. Programming errors: These are programming and configuration errors in the user application, like incorrect usage of the SDK(such as passing wrong type to parameter/function)
 *  2. API errors: These include recoverable errors that occur within the SDK implementation.
 *
 * @group Shared
 * @category Types
 */
abstract class APIResponseErrorBase extends Error {
    service: string;
    status: number | undefined;

    constructor(error: ErrorObjAPI, service: string) {
        super(error.message);
        this.service = service;
        this.status = error.status;

        if (error.data) {
            this.message = this.transformError(error.data);
        }

        /*
         * We use as message what returns from API if any, otherwise we have our APIErrorCode as a fallback
         * Check if there is a status and if the status exists in the mapped API error types
         */
        if (this.status && APIErrorCode[this.status]) {
            this.message = APIErrorCode[this.status];
        }
    }

    abstract transformError(data: any): string;
}

export class GeocodeAPIParseErrorResponse extends APIResponseErrorBase {
    constructor(error: ErrorObjAPI, service: string) {
        super(error, service);
    }

    transformError(data: GeocodeAPIResponseError): string {
        return data.errorText;
    }
}

export class RoutingAPIParseErrorResponse extends APIResponseErrorBase {
    constructor(error: ErrorObjAPI, service: string) {
        super(error, service);
    }

    transformError(data: RoutingAPIResponseError): string {
        return data.error.description;
    }
}

export class DefaultAPIParseErrorResponse extends APIResponseErrorBase {
    constructor(error: ErrorObjAPI, service: string) {
        super(error, service);
    }

    transformError(data: DefaultAPIResponseError): string {
        return data.error;
    }
}

/**
 * @ignore
 * Parse error API response object returned by generatError function
 * @param error The object error generated by generateError function
 * @param serviceName The name of the service.
 */
export const parseAPIErrorResponse = (error: ErrorObjAPI, serviceName: string) => {
    if (serviceName === "Geocode") {
        return new GeocodeAPIParseErrorResponse(error, serviceName);
    } else if (serviceName === "Routing") {
        return new RoutingAPIParseErrorResponse(error, serviceName);
    } else {
        return new DefaultAPIParseErrorResponse(error, serviceName);
    }
};

/**
 * @ignore
 * Generate error for APIResponse, any other error type will be returned as it is.
 * @param error The error captured by a catch function.
 * @param serviceName The name of the service.
 */
export const generateError = (error: unknown, serviceName: string) => {
    if (error instanceof AxiosError) {
        const errorObj = Object.assign(
            {},
            {
                status: error.response?.status,
                data: error.response?.data,
                message: error.message
            }
        );

        return parseAPIErrorResponse(errorObj, serviceName);
    }

    return error;
};
