/**
 * @module agent-toolkit-tools
 */

import { sectionTypes } from '@tomtom-org/maps-sdk/core';
import type { ToolEntry, ToolState } from '../types';

// --- MapLibre tools ---
import {
    executeExecuteMaplibreCode,
    executeFlyTo,
    executeGetMapStyleLayers,
    executeGetViewport,
    executeMaplibreCodeDescription,
    executeMaplibreCodeOutputSchema,
    executeMaplibreCodeSchema,
    executeSetLayoutProperties,
    executeSetPaintProperties,
    executeSetPitchBearing,
    executeZoomInOrOut,
    flyToDescription,
    flyToOutputSchema,
    flyToSchema,
    getMapStyleLayersDescription,
    getMapStyleLayersOutputSchema,
    getMapStyleLayersSchema,
    getViewportDescription,
    getViewportOutputSchema,
    getViewportSchema,
    setLayoutPropertiesDescription,
    setLayoutPropertiesOutputSchema,
    setLayoutPropertiesSchema,
    setPaintPropertiesDescription,
    setPaintPropertiesOutputSchema,
    setPaintPropertiesSchema,
    setPitchBearingDescription,
    setPitchBearingOutputSchema,
    setPitchBearingSchema,
    zoomInOrOutDescription,
    zoomInOrOutOutputSchema,
    zoomInOrOutSchema,
} from './maplibre';

// --- Service tools ---
import {
    addStopToRouteDescription,
    addStopToRouteOutputSchema,
    addStopToRouteSchema,
    discoverPlacesDescription,
    discoverPlacesOutputSchema,
    discoverPlacesSchema,
    executeAddStopToRoute,
    executeDiscoverPlaces,
    executeFindReachableArea,
    executeGetPoiCategoryCodes,
    executeGetTrafficAreaAnalytics,
    executeGetTrafficIncidents,
    executeLocatePlace,
    executeQueryTrafficAnalytics,
    executeRemoveStopFromRoute,
    executeReverseGeocode,
    executeSearchAlongRoute,
    executeSetRouteLocations,
    executeSetRouteParameters,
    findReachableAreaDescription,
    findReachableAreaOutputSchema,
    findReachableAreaSchema,
    getPoiCategoryCodesDescription,
    getPoiCategoryCodesOutputSchema,
    getPoiCategoryCodesSchema,
    getTrafficAreaAnalyticsDescription,
    getTrafficAreaAnalyticsOutputSchema,
    getTrafficAreaAnalyticsSchema,
    getTrafficIncidentsDescription,
    getTrafficIncidentsOutputSchema,
    getTrafficIncidentsSchema,
    locatePlaceDescription,
    locatePlaceOutputSchema,
    locatePlaceSchema,
    queryTrafficAnalyticsDescription,
    queryTrafficAnalyticsOutputSchema,
    queryTrafficAnalyticsSchema,
    removeStopFromRouteDescription,
    removeStopFromRouteOutputSchema,
    removeStopFromRouteSchema,
    reverseGeocodeDescription,
    reverseGeocodeOutputSchema,
    reverseGeocodeSchema,
    searchAlongRouteDescription,
    searchAlongRouteOutputSchema,
    searchAlongRouteSchema,
    setRouteLocationsDescription,
    setRouteLocationsOutputSchema,
    setRouteLocationsSchema,
    setRouteParametersDescription,
    setRouteParametersOutputSchema,
    setRouteParametersSchema,
} from './services';

// --- State tools ---
import {
    executeGetCurrentWaypoints,
    executeRecallPlaces,
    executeRecallRanges,
    executeRecallRoutes,
    getCurrentWaypointsDescription,
    getCurrentWaypointsOutputSchema,
    getCurrentWaypointsSchema,
    recallPlacesDescription,
    recallPlacesOutputSchema,
    recallPlacesSchema,
    recallRangesDescription,
    recallRangesOutputSchema,
    recallRangesSchema,
    recallRoutesDescription,
    recallRoutesOutputSchema,
    recallRoutesSchema,
} from './state';

// --- TomTom Map tools ---
import {
    clearMapDescription,
    clearMapOutputSchema,
    clearMapSchema,
    executeClearMap,
    executeFitRouteSection,
    executeGetShownIncidents,
    executeGetShownPlaces,
    executeGetShownRouteSections,
    executeGetShownRoutes,
    executeGetShownRouteTrafficIncidents,
    executeGetShownWaypoints,
    executeGetStandardMapStyles,
    executeSetLanguage,
    executeSetMapStandardStyle,
    executeSetRouteTheme,
    executeShowPlaces,
    executeShowRoutes,
    executeShowTrafficAreaAnalytics,
    executeShowWaypoints,
    executeToggleBaseMapLayerGroups,
    executeTogglePOIs,
    executeToggleTrafficFlow,
    executeToggleTrafficIncidents,
    fitRouteSectionDescription,
    fitRouteSectionOutputSchema,
    fitRouteSectionSchema,
    getShownIncidentsDescription,
    getShownIncidentsOutputSchema,
    getShownIncidentsSchema,
    getShownPlacesDescription,
    getShownPlacesOutputSchema,
    getShownPlacesSchema,
    getShownRouteSectionsDescription,
    getShownRouteSectionsOutputSchema,
    getShownRouteSectionsSchema,
    getShownRoutesDescription,
    getShownRoutesOutputSchema,
    getShownRoutesSchema,
    getShownRouteTrafficIncidentsDescription,
    getShownRouteTrafficIncidentsOutputSchema,
    getShownRouteTrafficIncidentsSchema,
    getShownWaypointsDescription,
    getShownWaypointsOutputSchema,
    getShownWaypointsSchema,
    getStandardMapStylesDescription,
    getStandardMapStylesOutputSchema,
    getStandardMapStylesSchema,
    setLanguageDescription,
    setLanguageOutputSchema,
    setLanguageSchema,
    setMapStandardStyleDescription,
    setMapStandardStyleOutputSchema,
    setMapStandardStyleSchema,
    setRouteThemeDescription,
    setRouteThemeOutputSchema,
    setRouteThemeSchema,
    showPlacesDescription,
    showPlacesOutputSchema,
    showPlacesSchema,
    showRouteDescription,
    showRouteOutputSchema,
    showRouteSchema,
    showTrafficAreaAnalyticsDescription,
    showTrafficAreaAnalyticsOutputSchema,
    showTrafficAreaAnalyticsSchema,
    showWaypointsDescription,
    showWaypointsOutputSchema,
    showWaypointsSchema,
    toggleBaseMapLayerGroupsDescription,
    toggleBaseMapLayerGroupsOutputSchema,
    toggleBaseMapLayerGroupsSchema,
    togglePOIsDescription,
    togglePOIsOutputSchema,
    togglePOIsSchema,
    toggleTrafficFlowDescription,
    toggleTrafficFlowOutputSchema,
    toggleTrafficFlowSchema,
    toggleTrafficIncidentsDescription,
    toggleTrafficIncidentsOutputSchema,
    toggleTrafficIncidentsSchema,
} from './tomtom-map';

// --- Utility tools ---
import {
    calculateBBoxDescription,
    calculateBBoxSchema,
    executeCalculateBBox,
    executeFormatDistance,
    executeFormatDuration,
    executeGetCurrentLocation,
    executeGetRouteProgress,
    executeGetSectionBBox,
    executeGetSectionProgress,
    formatDistanceDescription,
    formatDistanceSchema,
    formatDurationDescription,
    formatDurationSchema,
    getCurrentLocationDescription,
    getCurrentLocationOutputSchema,
    getCurrentLocationSchema,
    getRouteProgressDescription,
    getRouteProgressSchema,
    getSectionBBoxDescription,
    getSectionBBoxOutputSchema,
    getSectionBBoxSchema,
    getSectionProgressDescription,
    getSectionProgressSchema,
    helpDescription,
    helpOutputSchema,
    helpSchema,
} from './utilities';

/**
 * Default tool set for the agent toolkit.
 * Included automatically by createMapAgent unless includeDefaultTools is false.
 * Use resolveTools() for manual composition outside createMapAgent.
 */
export const DEFAULT_TOOLS = {
    locatePlace: {
        description: locatePlaceDescription,
        classificationPrompt:
            'Resolve a single location string (landmark, city, address) to a place without showing it; optionally stages a waypoint slot.',
        inputSchema: locatePlaceSchema,
        outputSchema: locatePlaceOutputSchema,
        execute: executeLocatePlace,
        tags: ['locate', 'place', 'location', 'waypoint'],
        examples: [
            'locatePlace("Buckingham Palace", where: "within-map-bounds", waypointIndex: 0)',
            'locatePlace("Tower Bridge", where: "nearby-map-center", waypointIndex: 1)',
            'locatePlace("Westminster Abbey", where: "anywhere")',
            'locatePlace("Central Station", where: { position: [4.9, 52.37] })',
        ],
        examplePrompts: ['Where is the Louvre?', 'Find the nearest train station', 'Locate Big Ben'],
        relatedTools: ['setRouteLocations', 'addStopToRoute', 'getCurrentWaypoints', 'recallPlaces'],
    },
    reverseGeocode: {
        description: reverseGeocodeDescription,
        classificationPrompt:
            'Convert [lng, lat] coordinates to an address; use after map clicks or any tool that returns a position.',
        inputSchema: reverseGeocodeSchema,
        outputSchema: reverseGeocodeOutputSchema,
        execute: executeReverseGeocode,
        tags: ['location', 'place'],
        examples: ['reverseGeocode({ position: [4.9, 52.4] })'],
        examplePrompts: ["What's the address at this point?", 'What street is at these coordinates?'],
        relatedTools: ['getViewport', 'getCurrentLocation', 'showPlaces', 'locatePlace'],
    },
    discoverPlaces: {
        description: discoverPlacesDescription,
        classificationPrompt:
            'Search for multiple places by text query or POI category within an area; call showPlaces to display results.',
        inputSchema: discoverPlacesSchema,
        outputSchema: discoverPlacesOutputSchema,
        execute: executeDiscoverPlaces,
        tags: ['discover', 'place', 'location'],
        examples: [
            'discoverPlaces(query: "coffee", position: [4.9, 52.4])',
            'discoverPlaces(poiCategories: ["ITALIAN_RESTAURANT"])  // category-only, no query needed',
            'discoverPlaces(query: "hotel", boundingBox: [4.8, 52.3, 5.0, 52.5])',
            'discoverPlaces(query: "parking", boundingBox: geoJsonFeature)',
            'discoverPlaces({ query: "coffee", withinRange: "ranges-0" })',
        ],
        examplePrompts: [
            'Find coffee shops near me',
            'Search for Italian restaurants in Amsterdam',
            'Show me parking nearby',
            'Find coffee shops within the range I just calculated',
        ],
        relatedTools: ['getPOICategoryCodes', 'showPlaces', 'locatePlace', 'getViewport', 'findReachableArea'],
    },
    setRouteLocations: {
        description: setRouteLocationsDescription,
        classificationPrompt:
            'Set route waypoints by resolving location queries and trigger a recalculation (minimum: origin + destination).',
        inputSchema: setRouteLocationsSchema,
        outputSchema: setRouteLocationsOutputSchema,
        execute: executeSetRouteLocations,
        tags: ['route', 'waypoint', 'location'],
        examples: [
            'setRouteLocations({ locations: [{ query: "Amsterdam" }, { query: "Brussels" }] })',
            'setRouteLocations({ locations: [{ query: "Eiffel Tower" }, { query: "Louvre Museum" }, { query: "Notre Dame" }] })',
            'setRouteLocations({ locations: [{ query: "5th Ave, New York", locationType: "default" }, { query: "JFK Airport", locationType: "default" }] })',
        ],
        examplePrompts: [
            'Get directions from Paris to Lyon',
            'Route me from Amsterdam to Brussels',
            'Navigate from here to the airport',
        ],
        relatedTools: ['setRouteParameters', 'showRoute', 'addStopToRoute', 'removeStopFromRoute'],
    },
    setRouteParameters: {
        description: setRouteParametersDescription,
        classificationPrompt:
            'Configure route options (alternatives, type, avoidances, departure/arrival time) and trigger recalculation if locations are set.',
        inputSchema: setRouteParametersSchema,
        outputSchema: setRouteParametersOutputSchema,
        execute: executeSetRouteParameters,
        tags: ['route'],
        examples: [
            'setRouteParameters({ maxAlternatives: 2 })',
            'setRouteParameters({ costModel: { routeType: "fast", avoid: ["tollRoads"] } })',
            'setRouteParameters({ when: { option: "departAt", date: "2025-06-01T09:00:00Z" } })',
        ],
        examplePrompts: ['Avoid toll roads', 'Find the fastest route', 'Show 2 alternative routes', 'Depart at 9am'],
        relatedTools: ['setRouteLocations', 'showRoute'],
    },
    addStopToRoute: {
        description: addStopToRouteDescription,
        classificationPrompt: 'Insert a stop at the optimal position in the current route and recalculate.',
        inputSchema: addStopToRouteSchema,
        outputSchema: addStopToRouteOutputSchema,
        execute: executeAddStopToRoute,
        tags: ['route', 'waypoint'],
        examples: [
            'addStopToRoute(location: "Westminster Abbey")',
            'addStopToRoute(location: "gas station near route")',
            'addStopToRoute()  // use the most recently resolved or shown place',
        ],
        examplePrompts: ['Add a stop at Westminster Abbey', 'Add a coffee break to my route'],
        relatedTools: ['locatePlace', 'setRouteLocations', 'showRoute', 'removeStopFromRoute'],
        dependsOn: ['setRouteLocations'],
    },
    removeStopFromRoute: {
        description: removeStopFromRouteDescription,
        classificationPrompt: 'Remove a stop by index from the current route and recalculate.',
        inputSchema: removeStopFromRouteSchema,
        outputSchema: removeStopFromRouteOutputSchema,
        execute: executeRemoveStopFromRoute,
        tags: ['route', 'waypoint'],
        examples: ['removeStopFromRoute(1)', 'removeStopFromRoute(2, 1)'],
        examplePrompts: ['Remove the second stop from my route', 'Delete the Utrecht stop'],
        relatedTools: ['addStopToRoute', 'setRouteLocations', 'showRoute'],
        dependsOn: ['setRouteLocations'],
    },
    getPOICategoryCodes: {
        description: getPoiCategoryCodesDescription,
        classificationPrompt:
            'Resolve natural-language category names (e.g. "gym", "italian food") to POICategory codes for discoverPlaces.',
        inputSchema: getPoiCategoryCodesSchema,
        outputSchema: getPoiCategoryCodesOutputSchema,
        execute: executeGetPoiCategoryCodes,
        tags: ['discover', 'place'],
        examples: [
            'getPOICategoryCodes()',
            'getPOICategoryCodes(filters: ["gym"])',
            'getPOICategoryCodes(filters: ["italian restaurant"])  // multi-word phrase, spaces removed before matching',
            'getPOICategoryCodes(filters: ["restaurant"], language: "fr-FR")',
        ],
        examplePrompts: ['What POI categories are available?', "What's the code for gym?"],
        relatedTools: ['discoverPlaces', 'togglePOIs'],
    },
    getTrafficIncidents: {
        description: getTrafficIncidentsDescription,
        classificationPrompt:
            'Fetch traffic incidents by bbox or IDs without showing them; returns category, severity, and delay details.',
        inputSchema: getTrafficIncidentsSchema,
        outputSchema: getTrafficIncidentsOutputSchema,
        execute: executeGetTrafficIncidents,
        tags: ['traffic', 'location'],
        examples: [
            'getTrafficIncidents({ bbox: [4.728, 52.278, 5.080, 52.479] })',
            'getTrafficIncidents({ ids: ["incident-id-1", "incident-id-2"] })',
            'getTrafficIncidents({ bbox: [...], categoryFilter: ["accident", "jam"] })',
            'getTrafficIncidents({ bbox: [...], categoryFilter: ["roadworks"], timeValidityFilter: ["future"] })',
        ],
        examplePrompts: ['Fetch traffic incidents in Amsterdam', 'Any accidents in this area?'],
        relatedTools: ['getShownIncidents', 'toggleTrafficIncidents', 'calculateBBox', 'getViewport'],
    },
    getTrafficAreaAnalytics: {
        description: getTrafficAreaAnalyticsDescription,
        classificationPrompt:
            'Fetch historical traffic analytics (speed, congestion, travel time) for an area; use queryTrafficAnalytics to drill down.',
        inputSchema: getTrafficAreaAnalyticsSchema,
        outputSchema: getTrafficAreaAnalyticsOutputSchema,
        execute: executeGetTrafficAreaAnalytics,
        tags: ['traffic', 'location'],
        examples: [
            "getTrafficAreaAnalytics({ bbox: [4.728, 52.278, 5.080, 52.479], metrics: ['speed', 'congestionLevel'], startDate: '2025-03-01', endDate: '2025-03-07' })",
            "getTrafficAreaAnalytics({ bbox: [...], metrics: ['congestionLevel'], hours: [7,8,9,17,18] })",
        ],
        examplePrompts: [
            'What was the average congestion in Amsterdam last week?',
            'Analyze traffic patterns during rush hour in this area',
            'Show me historical speed data for the city center',
        ],
        relatedTools: ['queryTrafficAnalytics', 'showTrafficAreaAnalytics', 'calculateBBox', 'getViewport'],
        dependsOn: ['locatePlace'],
    },
    queryTrafficAnalytics: {
        description: queryTrafficAnalyticsDescription,
        classificationPrompt:
            'Query cached traffic analytics data or check what metric/mode is currently displayed on the map.',
        inputSchema: queryTrafficAnalyticsSchema,
        outputSchema: queryTrafficAnalyticsOutputSchema,
        execute: executeQueryTrafficAnalytics,
        tags: ['traffic', 'location'],
        examples: [
            "queryTrafficAnalytics({ granularity: 'daily' })",
            "queryTrafficAnalytics({ granularity: 'hourly', hourStart: 7, hourEnd: 9, metric: 'congestionLevel' })",
            "queryTrafficAnalytics({ granularity: 'average', dayOfWeek: [6, 7] })",
        ],
        // NOTE: "What am I looking at?" awareness should be handled at a higher level
        // (e.g. system prompt or state summary injected into context), not per-tool examplePrompts.
        // Current approach works but doesn't scale — every stateful tool would need similar hints.
        examplePrompts: [
            'Show me the daily breakdown',
            'What was rush hour congestion?',
            'Which day had the worst traffic?',
            'What metric am I looking at?',
            'What is currently shown on the map?',
        ],
        relatedTools: ['getTrafficAreaAnalytics', 'showTrafficAreaAnalytics'],
        dependsOn: ['getTrafficAreaAnalytics'],
    },
    showPlaces: {
        description: showPlacesDescription,
        classificationPrompt: 'Display the most recent discoverPlaces/locatePlace results as markers on the map.',
        inputSchema: showPlacesSchema,
        outputSchema: showPlacesOutputSchema,
        execute: executeShowPlaces,
        tags: ['place', 'location'],
        examples: ['showPlaces()', 'showPlaces(false)'],
        examplePrompts: ['Show the results on the map', 'Pin the search results', 'Display these places'],
        relatedTools: ['discoverPlaces', 'locatePlace', 'reverseGeocode', 'clearMap', 'flyTo'],
        dependsOn: ['discoverPlaces', 'locatePlace'],
    },
    showRoute: {
        description: showRouteDescription,
        classificationPrompt: 'Render the most recently calculated route on the map and fit the camera to it.',
        inputSchema: showRouteSchema,
        outputSchema: showRouteOutputSchema,
        execute: executeShowRoutes,
        tags: ['route', 'waypoint'],
        examples: ['showRoute()', 'showRoute({ selectedIndex: 1 })', 'showRoute({ fitBounds: false })'],
        examplePrompts: ['Draw the route on the map', 'Show the directions', 'Display the calculated route'],
        relatedTools: ['setRouteLocations', 'getShownRouteSections', 'clearMap'],
        dependsOn: ['setRouteLocations'],
    },
    showTrafficAreaAnalytics: {
        description: showTrafficAreaAnalyticsDescription,
        classificationPrompt:
            'Render traffic analytics as hexgrid, heatmap, or tiles with custom colors, filtering, height, and tooltip.',
        inputSchema: showTrafficAreaAnalyticsSchema,
        outputSchema: showTrafficAreaAnalyticsOutputSchema,
        execute: executeShowTrafficAreaAnalytics,
        tags: ['traffic', 'map style'],
        examples: [
            'showTrafficAreaAnalytics()',
            "showTrafficAreaAnalytics({ mode: 'hexgrid-2d', metric: 'speed', colorTheme: 'heat' })",
            'showTrafficAreaAnalytics({ filter: { min: 50 } })',
            "showTrafficAreaAnalytics({ scaleMode: 'currentRange', heightScale: 200 })",
            'showTrafficAreaAnalytics({ visible: false })',
        ],
        examplePrompts: [
            'Show it on the map',
            'Visualize the congestion',
            'Only show areas with congestion above 50%',
            'Normalize height to the current data range',
            'Switch to heatmap view',
        ],
        relatedTools: ['getTrafficAreaAnalytics', 'queryTrafficAnalytics', 'toggleTrafficFlow', 'clearMap'],
        dependsOn: ['getTrafficAreaAnalytics'],
    },
    showWaypoints: {
        description: showWaypointsDescription,
        classificationPrompt: 'Display staged origin/stop/destination markers without drawing the route line.',
        inputSchema: showWaypointsSchema,
        outputSchema: showWaypointsOutputSchema,
        execute: executeShowWaypoints,
        tags: ['waypoint', 'route'],
        examples: ['showWaypoints()'],
        examplePrompts: ['Show the waypoints on the map', 'Mark my route stops'],
        relatedTools: ['setRouteLocations', 'showRoute', 'getShownWaypoints', 'clearMap'],
        dependsOn: ['setRouteLocations', 'locatePlace'],
    },
    getShownPlaces: {
        description: getShownPlacesDescription,
        classificationPrompt:
            'Return places currently displayed on the map (available after showPlaces or locatePlace).',
        inputSchema: getShownPlacesSchema,
        outputSchema: getShownPlacesOutputSchema,
        execute: executeGetShownPlaces,
        tags: ['place', 'location'],
        examples: ['getShownPlaces()'],
        examplePrompts: ['What places are on the map?', 'List the pinned locations'],
        relatedTools: ['showPlaces', 'clearMap', 'locatePlace', 'reverseGeocode'],
        dependsOn: ['showPlaces'],
    },
    getShownRoutes: {
        description: getShownRoutesDescription,
        classificationPrompt: 'Return routes currently rendered on the map (available after showRoute).',
        inputSchema: getShownRoutesSchema,
        outputSchema: getShownRoutesOutputSchema,
        execute: executeGetShownRoutes,
        tags: ['route'],
        examples: ['getShownRoutes()'],
        examplePrompts: ['What routes are displayed?', 'Is there a route on the map?'],
        relatedTools: ['showRoute', 'clearMap'],
        dependsOn: ['showRoute'],
    },
    getShownWaypoints: {
        description: getShownWaypointsDescription,
        classificationPrompt:
            'Return waypoint markers currently shown on the map (available after showRoute or showWaypoints).',
        inputSchema: getShownWaypointsSchema,
        outputSchema: getShownWaypointsOutputSchema,
        execute: executeGetShownWaypoints,
        tags: ['waypoint', 'route'],
        examples: ['getShownWaypoints()'],
        examplePrompts: ['What waypoints are shown?', 'List the stops on the map'],
        relatedTools: ['showRoute', 'clearMap'],
        dependsOn: ['showRoute', 'showWaypoints'],
    },
    getShownRouteTrafficIncidents: {
        description: getShownRouteTrafficIncidentsDescription,
        classificationPrompt: 'Return traffic incidents overlaid on the shown route.',
        inputSchema: getShownRouteTrafficIncidentsSchema,
        outputSchema: getShownRouteTrafficIncidentsOutputSchema,
        execute: executeGetShownRouteTrafficIncidents,
        tags: ['traffic', 'route'],
        examples: ['getShownRouteTrafficIncidents()'],
        examplePrompts: ['What traffic incidents are on my route?', 'Any delays along the route?'],
        relatedTools: ['showRoute', 'clearMap', 'setRouteLocations'],
        dependsOn: ['showRoute'],
    },
    getShownRouteSections: {
        description: getShownRouteSectionsDescription,
        classificationPrompt:
            'Return sections of a given type (toll, country, motorway, traffic) from the shown route.',
        inputSchema: getShownRouteSectionsSchema,
        outputSchema: getShownRouteSectionsOutputSchema,
        execute: executeGetShownRouteSections,
        tags: ['route', 'location', ...sectionTypes],
        examples: [
            'getShownRouteSections("toll")',
            'getShownRouteSections("country")',
            'getShownRouteSections("traffic")',
            'getShownRouteSections("motorway")',
        ],
        examplePrompts: [
            'What countries does the route pass through?',
            'Show me the toll sections',
            'List the motorway sections on my route',
        ],
        relatedTools: ['showRoute', 'getShownRoutes', 'getShownRouteTrafficIncidents', 'fitRouteSection'],
        dependsOn: ['showRoute'],
    },
    getShownIncidents: {
        description: getShownIncidentsDescription,
        classificationPrompt:
            'Return real-time incidents currently visible in the map viewport (rendered on map, not fetched from service).',
        inputSchema: getShownIncidentsSchema,
        outputSchema: getShownIncidentsOutputSchema,
        execute: executeGetShownIncidents,
        tags: ['traffic', 'location'],
        examples: ['getShownIncidents()'],
        examplePrompts: ['What traffic incidents are visible?', 'Any incidents in the current view?'],
        relatedTools: ['toggleTrafficIncidents', 'flyTo', 'getViewport'],
        dependsOn: ['toggleTrafficIncidents'],
    },
    clearMap: {
        description: clearMapDescription,
        classificationPrompt: 'Remove displayed places, routes, or all features from the map.',
        inputSchema: clearMapSchema,
        outputSchema: clearMapOutputSchema,
        execute: executeClearMap,
        tags: ['place', 'route', 'map style'],
        examples: ['clearMap()', 'clearMap(["places"])', 'clearMap(["places", "routes"])'],
        examplePrompts: ['Clear the map', 'Remove all markers', 'Start fresh'],
        relatedTools: ['showPlaces', 'showRoute'],
    },
    flyTo: {
        description: flyToDescription,
        classificationPrompt:
            'Move the camera to a bounding box or specific position; use after locating places or computing bounds.',
        inputSchema: flyToSchema,
        outputSchema: flyToOutputSchema,
        execute: executeFlyTo,
        tags: ['location', 'map style'],
        examples: [
            'flyTo({ where: { boundingBox: [4.8, 52.3, 5.0, 52.5] } })',
            'flyTo({ where: { boundingBox: [4.8, 52.3, 5.0, 52.5], padding: 100 } })',
            'flyTo({ where: { position: [4.9, 52.4], zoom: 14 } })',
        ],
        examplePrompts: ['Go to Berlin', 'Center the map on Rome', 'Fly to these coordinates'],
        relatedTools: ['getViewport', 'locatePlace', 'showPlaces', 'showRoute', 'calculateBBox'],
    },
    fitRouteSection: {
        description: fitRouteSectionDescription,
        classificationPrompt:
            'Fit the camera to a specific route section by type and ID; use getShownRouteSections for valid IDs.',
        inputSchema: fitRouteSectionSchema,
        outputSchema: fitRouteSectionOutputSchema,
        execute: executeFitRouteSection,
        tags: ['route', 'map style', ...sectionTypes],
        examples: ['fitRouteSection("country", "NLD-section-1")', 'fitRouteSection("traffic", "traffic-1", 100)'],
        examplePrompts: ['Zoom to the toll section', 'Fit the Netherlands part of the route in view'],
        relatedTools: ['flyTo', 'showRoute', 'getShownRoutes', 'getShownRouteTrafficIncidents'],
        dependsOn: ['getShownRouteSections'],
    },
    getViewport: {
        description: getViewportDescription,
        classificationPrompt:
            'Return the map center, zoom, and bounding box; use for area-relative queries like "in this area" or "near the map center".',
        inputSchema: getViewportSchema,
        outputSchema: getViewportOutputSchema,
        execute: executeGetViewport,
        tags: ['location', 'map style'],
        examples: ['getViewport()'],
        examplePrompts: [
            'Where is the map centered?',
            "What's the current map area?",
            'What are the current map bounds?',
        ],
        relatedTools: ['locatePlace', 'flyTo', 'discoverPlaces', 'reverseGeocode', 'getTrafficIncidents'],
    },
    recallPlaces: {
        description: recallPlacesDescription,
        classificationPrompt: 'Return the history of locatePlace/discoverPlaces calls made in this session.',
        inputSchema: recallPlacesSchema,
        outputSchema: recallPlacesOutputSchema,
        execute: executeRecallPlaces,
        tags: ['place', 'location'],
        examples: ['recallPlaces()', 'recallPlaces({ id: "places-0" })'],
        examplePrompts: [
            'What places did I search for?',
            'Show the coffee shops from earlier',
            'What was the first place we looked up?',
        ],
        relatedTools: ['discoverPlaces', 'locatePlace', 'reverseGeocode', 'showPlaces'],
        dependsOn: ['locatePlace', 'discoverPlaces'],
    },
    recallRoutes: {
        description: recallRoutesDescription,
        classificationPrompt: 'Return previously calculated routes from this session.',
        inputSchema: recallRoutesSchema,
        outputSchema: recallRoutesOutputSchema,
        execute: executeRecallRoutes,
        tags: ['route'],
        examples: ['recallRoutes()', 'recallRoutes({ id: "routes-0" })'],
        examplePrompts: [
            'What routes have I calculated?',
            'Show the first route we planned',
            'What was the route to Schiphol?',
        ],
        relatedTools: ['setRouteLocations', 'showRoute', 'getCurrentWaypoints'],
        dependsOn: ['setRouteLocations'],
    },
    getCurrentWaypoints: {
        description: getCurrentWaypointsDescription,
        classificationPrompt:
            'Return the staged waypoint slots (origin, stops, destination) not yet committed to a route.',
        inputSchema: getCurrentWaypointsSchema,
        outputSchema: getCurrentWaypointsOutputSchema,
        execute: executeGetCurrentWaypoints,
        tags: ['waypoint', 'route'],
        examples: [
            'getCurrentWaypoints()',
            'getCurrentWaypoints({ slotIndex: 1 })',
            'getCurrentWaypoints({ includeEmptySlots: true })',
            'getCurrentWaypoints({ offset: 2, limit: 4 })',
        ],
        examplePrompts: ['What are my current route waypoints?', "What's my destination?", 'Show my staged stops'],
        relatedTools: ['locatePlace', 'setRouteLocations', 'showWaypoints', 'recallRoutes'],
    },
    getStandardMapStyles: {
        description: getStandardMapStylesDescription,
        classificationPrompt: 'List available standard map style IDs for use with setMapStandardStyle.',
        inputSchema: getStandardMapStylesSchema,
        outputSchema: getStandardMapStylesOutputSchema,
        execute: executeGetStandardMapStyles,
        tags: ['map style'],
        examples: ['getStandardMapStyles()'],
        examplePrompts: ['What map styles are available?', 'List the map themes'],
        relatedTools: ['setMapStandardStyle'],
    },
    setMapStandardStyle: {
        description: setMapStandardStyleDescription,
        classificationPrompt: 'Switch the map to a standard style preset (light, dark, satellite, driving, etc.).',
        inputSchema: setMapStandardStyleSchema,
        outputSchema: setMapStandardStyleOutputSchema,
        execute: executeSetMapStandardStyle,
        tags: ['map style'],
        examples: ['setMapStandardStyle("standardDark")', 'setMapStandardStyle("satellite")'],
        examplePrompts: ['Switch to dark mode', 'Use the satellite view', 'Change to the light theme'],
        relatedTools: ['getStandardMapStyles', 'setLanguage', 'toggleBaseMapLayerGroups', 'getMapStyleLayers'],
    },
    setRouteTheme: {
        description: setRouteThemeDescription,
        classificationPrompt:
            'Color the route line and waypoint icons; prefer over setPaintProperties for route styling.',
        inputSchema: setRouteThemeSchema,
        outputSchema: setRouteThemeOutputSchema,
        execute: executeSetRouteTheme,
        tags: ['route', 'map style'],
        examples: [
            'setRouteTheme({ mainColor: "#FF0000" })  // red route',
            'setRouteTheme({ mainColor: "coral" })',
            'setRouteTheme({ mainColor: "steelblue" })',
        ],
        examplePrompts: ['Make the route line red', 'Change the route color to blue', 'Style the route in coral'],
        relatedTools: ['showRoute', 'setRouteLocations', 'setPaintProperties'],
        dependsOn: ['showRoute'],
    },
    setLanguage: {
        description: setLanguageDescription,
        classificationPrompt: 'Change the language for map labels and all subsequent service API responses.',
        inputSchema: setLanguageSchema,
        outputSchema: setLanguageOutputSchema,
        execute: executeSetLanguage,
        tags: ['map style'],
        examples: ['setLanguage("fr-FR")', 'setLanguage("de-DE")'],
        examplePrompts: ['Show map labels in French', 'Switch the map to German', 'Use Spanish for place names'],
        relatedTools: ['setMapStandardStyle'],
    },
    toggleBaseMapLayerGroups: {
        description: toggleBaseMapLayerGroupsDescription,
        classificationPrompt:
            'Show or hide named base map layer groups (buildings3D, roadLabels, water, placeLabels, etc.).',
        inputSchema: toggleBaseMapLayerGroupsSchema,
        outputSchema: toggleBaseMapLayerGroupsOutputSchema,
        execute: executeToggleBaseMapLayerGroups,
        tags: ['map style'],
        examples: [
            'toggleBaseMapLayerGroups(false, ["buildings3D"])',
            'toggleBaseMapLayerGroups(true, ["roadLabels"])',
        ],
        examplePrompts: ['Hide 3D buildings', 'Show road labels', 'Toggle the building layer'],
        relatedTools: ['togglePOIs', 'getMapStyleLayers', 'setMapStandardStyle'],
    },
    togglePOIs: {
        description: togglePOIsDescription,
        classificationPrompt: 'Show or hide built-in map POI icons with optional category filtering.',
        inputSchema: togglePOIsSchema,
        outputSchema: togglePOIsOutputSchema,
        execute: executeTogglePOIs,
        tags: ['place', 'map style'],
        examples: [
            'togglePOIs({ allMapPOIsVisible: false })',
            'togglePOIs({ allMapPOIsVisible: true, filterCategories: { show: "only", values: ["RESTAURANT", "CAFE"] } })',
            'togglePOIs({ filterCategories: { show: "all_except", values: ["PARKING_GARAGE"] } })',
            'togglePOIs({ reset: true })',
        ],
        examplePrompts: ['Hide all POI icons', 'Show only restaurant POIs', 'Turn off parking icons'],
        relatedTools: ['toggleBaseMapLayerGroups', 'discoverPlaces', 'setMapStandardStyle'],
    },
    toggleTrafficFlow: {
        description: toggleTrafficFlowDescription,
        classificationPrompt:
            'Toggle REAL-TIME traffic flow (colored road segments for live speeds). Not historical analytics.',
        inputSchema: toggleTrafficFlowSchema,
        outputSchema: toggleTrafficFlowOutputSchema,
        execute: executeToggleTrafficFlow,
        tags: ['traffic', 'map style'],
        examples: ['toggleTrafficFlow(true)', 'toggleTrafficFlow(false)'],
        examplePrompts: ['Show traffic flow', 'Turn off traffic colors', 'Enable the congestion overlay'],
        relatedTools: ['toggleTrafficIncidents', 'setRouteLocations', 'getTrafficIncidents'],
    },
    toggleTrafficIncidents: {
        description: toggleTrafficIncidentsDescription,
        classificationPrompt:
            'Toggle REAL-TIME traffic incident markers and lines (accidents, jams, closures). Not historical analytics.',
        inputSchema: toggleTrafficIncidentsSchema,
        outputSchema: toggleTrafficIncidentsOutputSchema,
        execute: executeToggleTrafficIncidents,
        tags: ['traffic', 'map style'],
        examples: ['toggleTrafficIncidents(true)', 'toggleTrafficIncidents(false)'],
        examplePrompts: ['Show traffic incidents', 'Hide accident icons', 'Enable incident markers'],
        relatedTools: ['toggleTrafficFlow', 'getTrafficIncidents', 'getShownIncidents', 'setRouteLocations'],
    },
    getMapStyleLayers: {
        description: getMapStyleLayersDescription,
        classificationPrompt: 'List MapLibre layer IDs with their paint/layout properties for custom styling.',
        inputSchema: getMapStyleLayersSchema,
        outputSchema: getMapStyleLayersOutputSchema,
        execute: executeGetMapStyleLayers,
        tags: ['map style'],
        examples: ['getMapStyleLayers()', 'getMapStyleLayers("road")', 'getMapStyleLayers("water")'],
        examplePrompts: ['What are the paint properties of the water layer?', 'Show me the road layer layout'],
        relatedTools: ['setLayoutProperties', 'setPaintProperties'],
    },
    setLayoutProperties: {
        description: setLayoutPropertiesDescription,
        classificationPrompt: 'Set MapLibre layout properties (visibility, text-field, icon-size) on named layers.',
        inputSchema: setLayoutPropertiesSchema,
        outputSchema: setLayoutPropertiesOutputSchema,
        execute: executeSetLayoutProperties,
        tags: ['map style'],
        examples: [
            'setLayoutProperties([{ layerId: "road-label", propertyName: "visibility", value: "none" }])',
            'setLayoutProperties([{ layerId: "poi-label", propertyName: "text-field", value: "{name}" }, { layerId: "poi-label", propertyName: "icon-size", value: 1.2 }])',
        ],
        examplePrompts: [
            'Hide the road-label layer',
            'Change the text size on building labels',
            'Make the city labels bigger',
        ],
        relatedTools: ['getMapStyleLayers', 'setPaintProperties'],
        dependsOn: ['getMapStyleLayers'],
    },
    setPaintProperties: {
        description: setPaintPropertiesDescription,
        classificationPrompt: 'Set MapLibre paint properties (colors, widths, opacity) on named layers.',
        inputSchema: setPaintPropertiesSchema,
        outputSchema: setPaintPropertiesOutputSchema,
        execute: executeSetPaintProperties,
        tags: ['map style'],
        examples: [
            'setPaintProperties([{ layerId: "water", propertyName: "fill-color", value: "#0000ff" }])',
            'setPaintProperties([{ layerId: "road", propertyName: "line-color", value: "#ff0000" }, { layerId: "road", propertyName: "line-width", value: 3 }])',
        ],
        examplePrompts: [
            'Make the water bright blue',
            'Change the road color to red',
            'Make buildings semi-transparent',
            'Make the country borders pink',
        ],
        relatedTools: ['getMapStyleLayers', 'setLayoutProperties', 'setRouteTheme'],
        dependsOn: ['getMapStyleLayers'],
    },
    setPitchBearing: {
        description: setPitchBearingDescription,
        classificationPrompt: 'Tilt (pitch) and/or rotate (bearing) the map camera for a 3D perspective.',
        inputSchema: setPitchBearingSchema,
        outputSchema: setPitchBearingOutputSchema,
        execute: executeSetPitchBearing,
        tags: ['map style'],
        examples: [
            'setPitchBearing({ pitch: 45 })',
            'setPitchBearing({ bearing: 90 })',
            'setPitchBearing({ pitch: 60, bearing: -45 })',
        ],
        examplePrompts: ['Tilt the map to 45 degrees', 'Rotate the map to face north', 'Set a 3D perspective view'],
        relatedTools: ['getViewport', 'locatePlace', 'flyTo'],
    },
    zoomInOrOut: {
        description: zoomInOrOutDescription,
        classificationPrompt: 'Adjust the map zoom level by a delta; positive zooms in, negative zooms out.',
        inputSchema: zoomInOrOutSchema,
        outputSchema: zoomInOrOutOutputSchema,
        execute: executeZoomInOrOut,
        tags: ['map style'],
        examples: ['zoomInOrOut({ delta: 2 })', 'zoomInOrOut({ delta: -1 })'],
        examplePrompts: ['Zoom in', 'Zoom out 2 levels', 'Get a wider view'],
        relatedTools: ['getViewport', 'flyTo'],
    },
    executeMaplibreCode: {
        description: executeMaplibreCodeDescription,
        classificationPrompt:
            'Execute any MapLibre JS code against the live map for maximum flexibility — use when no other tool covers the required operation.',
        inputSchema: executeMaplibreCodeSchema,
        outputSchema: executeMaplibreCodeOutputSchema,
        execute: executeExecuteMaplibreCode,
        tags: ['map style', 'maplibre', 'layers', 'sources', 'animation'],
        examples: [
            "executeMaplibreCode({ code: \"map.addSource('pts', { type: 'geojson', data: fc }); map.addLayer({ id: 'pts', type: 'circle', source: 'pts', paint: { 'circle-color': '#f00' } })\" })",
            'executeMaplibreCode({ code: "map.easeTo({ center: [4.9, 52.37], zoom: 14, duration: 2000 })" })',
            "executeMaplibreCode({ code: \"for (let i = 0; i <= 20; i++) { map.setPaintProperty('fill', 'fill-opacity', i / 20); await new Promise(r => setTimeout(r, 50)); }\" })",
            "executeMaplibreCode({ code: \"map.setFog({ color: 'white', 'horizon-blend': 0.1 })\" })",
        ],
        examplePrompts: [
            'Add a GeoJSON layer to the map',
            'Animate the map camera',
            'Fade in a layer gradually',
            'Set map fog or atmosphere',
            'Add a raster tile overlay',
        ],
        relatedTools: ['getMapStyleLayers', 'setLayoutProperties', 'setPaintProperties', 'flyTo'],
        dependsOn: ['getMapStyleLayers'],
    },
    calculateBBox: {
        description: calculateBBoxDescription,
        classificationPrompt:
            'Compute a [minLng, minLat, maxLng, maxLat] bounding box from GeoJSON features or tool results.',
        inputSchema: calculateBBoxSchema,
        execute: executeCalculateBBox,
        tags: ['utilities', 'location'],
        examples: ['calculateBBox(place)', 'calculateBBox(routes)', 'calculateBBox([place1, place2])'],
        examplePrompts: ["What's the bounding box of these places?", 'Calculate the extent of this route'],
        relatedTools: ['flyTo', 'getViewport', 'showPlaces', 'showRoute'],
    },
    formatDistance: {
        description: formatDistanceDescription,
        classificationPrompt:
            'Format meters into a human-readable string (e.g. "2.5 km"); use after tools that return distances.',
        inputSchema: formatDistanceSchema,
        execute: executeFormatDistance,
        tags: ['utilities', 'route'],
        examples: ['formatDistance(2500)', 'formatDistance(5000, "imperial_us")'],
        examplePrompts: ['Format 5000 meters as a distance', 'Convert meters to a readable string'],
        relatedTools: ['formatDuration', 'setRouteLocations', 'getSectionProgress', 'getRouteProgress'],
    },
    formatDuration: {
        description: formatDurationDescription,
        classificationPrompt:
            'Format seconds into a human-readable string (e.g. "1 h 30 min"); use after tools that return durations.',
        inputSchema: formatDurationSchema,
        execute: executeFormatDuration,
        tags: ['utilities', 'route'],
        examples: ['formatDuration(3600)', 'formatDuration(9000)'],
        examplePrompts: ['Format 3600 seconds as a duration', 'Convert seconds to hours and minutes'],
        relatedTools: ['formatDistance', 'setRouteLocations', 'getSectionProgress', 'getRouteProgress'],
    },
    getSectionProgress: {
        description: getSectionProgressDescription,
        classificationPrompt:
            'Return the distance and travel time for one or more sections of the shown route by type.',
        inputSchema: getSectionProgressSchema,
        execute: executeGetSectionProgress,
        tags: ['utilities', 'route', ...sectionTypes],
        examples: [
            'getSectionProgress({ sectionType: "country" })  // all country sections',
            'getSectionProgress({ sectionType: "traffic", ids: ["incident-id-1"] })',
            'getSectionProgress({ sectionType: "toll", ids: ["toll-1", "toll-2"] })',
        ],
        examplePrompts: ['How far is the toll section?', 'Travel time through France on this route'],
        relatedTools: ['setRouteLocations', 'fitRouteSection', 'formatDistance', 'formatDuration'],
        dependsOn: ['showRoute'],
    },
    getSectionBBox: {
        description: getSectionBBoxDescription,
        classificationPrompt: 'Return the bounding box of a specific route section; use with flyTo to frame it.',
        inputSchema: getSectionBBoxSchema,
        outputSchema: getSectionBBoxOutputSchema,
        execute: executeGetSectionBBox,
        tags: ['utilities', 'route', 'location', ...sectionTypes],
        examples: [
            'getSectionBBox({ sectionType: "country", id: "NLD-section-1" })',
            'getSectionBBox({ sectionType: "traffic", id: "traffic-1" })',
            'getSectionBBox({ sectionType: "toll", id: "toll-2" })',
        ],
        examplePrompts: ['Get the extent of the Netherlands section', 'Bounding box of the traffic incident'],
        relatedTools: ['flyTo', 'fitRouteSection', 'getSectionProgress', 'getShownRouteSections'],
        dependsOn: ['getShownRouteSections'],
    },
    getRouteProgress: {
        description: getRouteProgressDescription,
        classificationPrompt:
            'Return the position along the shown route at a given traveled time, distance, or clock time.',
        inputSchema: getRouteProgressSchema,
        execute: executeGetRouteProgress,
        tags: ['utilities', 'route', 'location'],
        examples: [
            'getRouteProgress(traveledTimeInSeconds: 600)',
            'getRouteProgress(traveledDistanceInMeters: 5000)',
            'getRouteProgress(clockTime: "2025-06-01T09:30:00Z")',
            'getRouteProgress(traveledTimeInSeconds: 300, routeIndex: 1)',
        ],
        examplePrompts: ['Where am I after 10 minutes of travel?', 'Position at 5km into the route'],
        relatedTools: ['setRouteLocations', 'getSectionProgress', 'formatDistance', 'formatDuration'],
        dependsOn: ['showRoute'],
    },
    getCurrentLocation: {
        description: getCurrentLocationDescription,
        classificationPrompt:
            'Get the user\'s physical GPS location from the browser; use for "near me" queries, not map center.',
        inputSchema: getCurrentLocationSchema,
        outputSchema: getCurrentLocationOutputSchema,
        execute: executeGetCurrentLocation,
        tags: ['utilities', 'location'],
        examples: ['getCurrentLocation()'],
        examplePrompts: ['Where am I?', 'Get my GPS location', 'Use my current position'],
        relatedTools: ['discoverPlaces', 'reverseGeocode', 'locatePlace'],
    },
    help: {
        description: helpDescription,
        classificationPrompt:
            'Return available capabilities in summary or searchable detail mode; call when the user asks what you can do.',
        inputSchema: helpSchema,
        outputSchema: helpOutputSchema,
        execute: async () => {
            throw new Error('help tool requires setupTools() — it needs resolved metadata from all tools.');
        },
        tags: ['utilities'],
        examples: [
            'help({ mode: "summary" })',
            'help({ mode: "detail", query: "traffic" })',
            'help({ mode: "detail", tag: "route" })',
            'help({ mode: "detail", query: "route", tag: "utilities" })',
        ],
        examplePrompts: ['What can you do?', 'Show me available tools', 'How do I search for places?'],
    },
    searchAlongRoute: {
        description: searchAlongRouteDescription,
        classificationPrompt: 'Search for POIs along a calculated route ranked by detour cost.',
        inputSchema: searchAlongRouteSchema,
        outputSchema: searchAlongRouteOutputSchema,
        execute: executeSearchAlongRoute,
        tags: ['search', 'route', 'place', 'detour', 'along-route'],
        examples: [
            'searchAlongRoute({ maxDetourTimeSeconds: 300, query: "coffee" })',
            'searchAlongRoute({ maxDetourTimeSeconds: 600, poiCategories: ["ELECTRIC_VEHICLE_STATION"], sortBy: "detourOffset" })',
            'searchAlongRoute({ maxDetourTimeSeconds: 300, routeIndex: 0, show: { markerType: "pin", zoomMode: "auto" } })',
        ],
        examplePrompts: [
            'Find gas stations along my route',
            'Show me coffee shops within 5 minutes off the route',
            'Any EV chargers I can reach from this route?',
            'I need a coffee stop on the way to the airport',
            'Find me a restaurant somewhere between here and Paris',
        ],
        relatedTools: ['setRouteLocations', 'recallRoutes', 'showPlaces', 'recallPlaces'],
        dependsOn: ['setRouteLocations'],
    },
    findReachableArea: {
        description: findReachableAreaDescription,
        classificationPrompt: 'Calculate isochrone/isodistance polygons showing how far you can travel from a point.',
        inputSchema: findReachableAreaSchema,
        outputSchema: findReachableAreaOutputSchema,
        execute: executeFindReachableArea,
        tags: ['reachable-range', 'isochrone', 'range', 'EV', 'coverage'],
        examples: [
            'findReachableArea({ origin: { query: "Amsterdam", locationType: "default" }, budgets: [{ type: "timeMinutes", value: 30 }], showOnMap: true })',
            'findReachableArea({ origin: { position: { lng: 4.9, lat: 52.3 } }, budgets: [{ type: "timeMinutes", value: 10 }, { type: "timeMinutes", value: 30 }], showOnMap: true, theme: "inverted" })',
            'findReachableArea({ origin: { query: "my location", locationType: "default" }, budgets: [{ type: "distanceKM", value: 50 }], showOnMap: false })',
        ],
        examplePrompts: [
            'Show me where I can reach in 30 minutes from Amsterdam',
            'What area is within 50 km of Berlin?',
            'Show 10, 20, 30 minute drive zones from here',
        ],
        relatedTools: ['recallRanges', 'locatePlace'],
    },
    recallRanges: {
        description: recallRangesDescription,
        classificationPrompt: 'Retrieve stored reachable range results from session history.',
        inputSchema: recallRangesSchema,
        outputSchema: recallRangesOutputSchema,
        execute: executeRecallRanges,
        tags: ['recall', 'reachable-range', 'state'],
        examples: ['recallRanges()', 'recallRanges({ id: "ranges-0" })'],
        examplePrompts: ['What range did I calculate earlier?', 'Recall the isochrone from Amsterdam'],
        relatedTools: ['findReachableArea'],
    },
} satisfies Record<string, ToolEntry<ToolState>>;

/** All valid default tool names, derived from {@link DEFAULT_TOOLS}. */
export const TOOL_NAMES = Object.keys(DEFAULT_TOOLS) as ToolName[];

/** Union of all default tool names. */
export type ToolName = keyof typeof DEFAULT_TOOLS;
