/**
 * @module agent-toolkit-tools
 */

import type { ToolDefinition } from '../types';

// --- MapLibre tools ---
import {
    executeExecuteMaplibreCode,
    executeFlyTo,
    executeGetMapStyleLayers,
    executeGetViewport,
    executeMaplibreCodeDescription,
    executeMaplibreCodeOutputSchema,
    executeMaplibreCodeSchema,
    executeSetLayoutProperties,
    executeSetPaintProperties,
    executeSetPitchBearing,
    executeZoomInOrOut,
    flyToDescription,
    flyToOutputSchema,
    flyToSchema,
    getMapStyleLayersDescription,
    getMapStyleLayersOutputSchema,
    getMapStyleLayersSchema,
    getViewportDescription,
    getViewportOutputSchema,
    getViewportSchema,
    setLayoutPropertiesDescription,
    setLayoutPropertiesOutputSchema,
    setLayoutPropertiesSchema,
    setPaintPropertiesDescription,
    setPaintPropertiesOutputSchema,
    setPaintPropertiesSchema,
    setPitchBearingDescription,
    setPitchBearingOutputSchema,
    setPitchBearingSchema,
    zoomInOrOutDescription,
    zoomInOrOutOutputSchema,
    zoomInOrOutSchema,
} from './maplibre';

// --- Service tools ---
import {
    addWaypointsToRouteDescription,
    addWaypointsToRouteOutputSchema,
    addWaypointsToRouteSchema,
    discoverPlacesBuilder,
    executeAddWaypointsToRoute,
    executeFindReachableAreas,
    executeGetPoiCategoryCodes,
    executeGetTrafficAreaAnalytics,
    executeGetTrafficIncidents,
    executeLocatePlace,
    executeRemoveWaypointsFromRoute,
    executeReplaceWaypointInRoute,
    executeReverseGeocode,
    executeSetRoute,
    findReachableAreasDescription,
    findReachableAreasOutputSchema,
    findReachableAreasSchema,
    getPoiCategoryCodesDescription,
    getPoiCategoryCodesOutputSchema,
    getPoiCategoryCodesSchema,
    getTrafficAreaAnalyticsDescription,
    getTrafficAreaAnalyticsOutputSchema,
    getTrafficAreaAnalyticsSchema,
    getTrafficIncidentsDescription,
    getTrafficIncidentsOutputSchema,
    getTrafficIncidentsSchema,
    locatePlaceDescription,
    locatePlaceOutputSchema,
    locatePlaceSchema,
    removeWaypointsFromRouteDescription,
    removeWaypointsFromRouteOutputSchema,
    removeWaypointsFromRouteSchema,
    replaceWaypointInRouteDescription,
    replaceWaypointInRouteOutputSchema,
    replaceWaypointInRouteSchema,
    reverseGeocodeDescription,
    reverseGeocodeOutputSchema,
    reverseGeocodeSchema,
    setRouteDescription,
    setRouteOutputSchema,
    setRouteSchema,
} from './services';

// --- State tools ---
import {
    analyseGeometriesDescription,
    analyseGeometriesOutputSchema,
    analyseGeometriesSchema,
    analyseIncidentsDescription,
    analyseIncidentsOutputSchema,
    analyseIncidentsSchema,
    analysePlacesBuilder,
    analyseRoutesDescription,
    analyseRoutesOutputSchema,
    analyseRoutesSchema,
    executeAnalyseGeometries,
    executeAnalyseIncidents,
    executeAnalyseRoutes,
    executeFocusIncidents,
    executeGetCurrentWaypoints,
    executeProcessGeometries,
    executeProcessRoutes,
    executeQueryTrafficAnalytics,
    executeRecallGeometries,
    executeRecallRanges,
    executeRecallRoutes,
    executeRecallState,
    executeResetState,
    executeSetEntryMode,
    executeStartTrafficIncidentsMonitor,
    executeStopTrafficIncidentsMonitor,
    focusIncidentsDescription,
    focusIncidentsOutputSchema,
    focusIncidentsSchema,
    getCurrentWaypointsDescription,
    getCurrentWaypointsOutputSchema,
    getCurrentWaypointsSchema,
    processGeometriesDescription,
    processGeometriesOutputSchema,
    processGeometriesSchema,
    processPlacesBuilder,
    processRoutesDescription,
    processRoutesOutputSchema,
    processRoutesSchema,
    queryTrafficAnalyticsDescription,
    queryTrafficAnalyticsOutputSchema,
    queryTrafficAnalyticsSchema,
    recallGeometriesDescription,
    recallGeometriesOutputSchema,
    recallGeometriesSchema,
    recallPlacesBuilder,
    recallRangesDescription,
    recallRangesOutputSchema,
    recallRangesSchema,
    recallRoutesDescription,
    recallRoutesOutputSchema,
    recallRoutesSchema,
    recallStateDescription,
    recallStateOutputSchema,
    recallStateSchema,
    resetStateDescription,
    resetStateOutputSchema,
    resetStateSchema,
    setEntryModeDescription,
    setEntryModeOutputSchema,
    setEntryModeSchema,
    startTrafficIncidentsMonitorDescription,
    startTrafficIncidentsMonitorOutputSchema,
    startTrafficIncidentsMonitorSchema,
    stopTrafficIncidentsMonitorDescription,
    stopTrafficIncidentsMonitorOutputSchema,
    stopTrafficIncidentsMonitorSchema,
} from './state';

// --- TomTom Map tools ---
import {
    clearMapDescription,
    clearMapOutputSchema,
    clearMapSchema,
    executeClearMap,
    executeGetShownIncidents,
    executeGetShownPlaces,
    executeGetShownRoutes,
    executeGetShownRouteTrafficIncidents,
    executeGetShownWaypoints,
    executeGetStandardMapStyles,
    executeSetLanguage,
    executeSetMapStandardStyle,
    executeSetRouteTheme,
    executeShowTrafficAreaAnalytics,
    executeShowWaypoints,
    executeToggleBaseMapLayerGroups,
    executeTogglePOIs,
    executeToggleTrafficFlow,
    executeToggleTrafficIncidents,
    executeUpdatePlacesDisplay,
    executeUpdateRoutesDisplay,
    getShownIncidentsDescription,
    getShownIncidentsOutputSchema,
    getShownIncidentsSchema,
    getShownPlacesDescription,
    getShownPlacesOutputSchema,
    getShownPlacesSchema,
    getShownRoutesDescription,
    getShownRoutesOutputSchema,
    getShownRoutesSchema,
    getShownRouteTrafficIncidentsDescription,
    getShownRouteTrafficIncidentsOutputSchema,
    getShownRouteTrafficIncidentsSchema,
    getShownWaypointsDescription,
    getShownWaypointsOutputSchema,
    getShownWaypointsSchema,
    getStandardMapStylesDescription,
    getStandardMapStylesOutputSchema,
    getStandardMapStylesSchema,
    setLanguageDescription,
    setLanguageOutputSchema,
    setLanguageSchema,
    setMapStandardStyleDescription,
    setMapStandardStyleOutputSchema,
    setMapStandardStyleSchema,
    setRouteThemeDescription,
    setRouteThemeOutputSchema,
    setRouteThemeSchema,
    showTrafficAreaAnalyticsDescription,
    showTrafficAreaAnalyticsOutputSchema,
    showTrafficAreaAnalyticsSchema,
    showWaypointsDescription,
    showWaypointsOutputSchema,
    showWaypointsSchema,
    toggleBaseMapLayerGroupsDescription,
    toggleBaseMapLayerGroupsOutputSchema,
    toggleBaseMapLayerGroupsSchema,
    togglePOIsDescription,
    togglePOIsOutputSchema,
    togglePOIsSchema,
    toggleTrafficFlowDescription,
    toggleTrafficFlowOutputSchema,
    toggleTrafficFlowSchema,
    toggleTrafficIncidentsDescription,
    toggleTrafficIncidentsOutputSchema,
    toggleTrafficIncidentsSchema,
    updatePlacesDisplayDescription,
    updatePlacesDisplayOutputSchema,
    updatePlacesDisplaySchema,
    updateRoutesDisplayDescription,
    updateRoutesDisplayOutputSchema,
    updateRoutesDisplaySchema,
} from './tomtom-map';

// --- Utility tools ---
import {
    calculateBBoxDescription,
    calculateBBoxSchema,
    executeCalculateBBox,
    executeFormatDistance,
    executeFormatDuration,
    executeGetCurrentLocation,
    formatDistanceDescription,
    formatDistanceSchema,
    formatDurationDescription,
    formatDurationSchema,
    getCurrentLocationDescription,
    getCurrentLocationOutputSchema,
    getCurrentLocationSchema,
    helpDescription,
    helpOutputSchema,
    helpSchema,
} from './utilities';

const defaultTools = {
    locatePlace: {
        description: locatePlaceDescription,
        classificationPrompt:
            'Resolve a single location string (landmark, city, address) to a place without showing it; optionally stages a waypoint slot. ' +
            'Do NOT call as a precursor to discoverPlaces — discoverPlaces resolves named areas itself via `where.query` (or `where.municipalities` / `where.placeId`).',
        inputSchema: locatePlaceSchema,
        outputSchema: locatePlaceOutputSchema,
        execute: executeLocatePlace,
        tags: ['locate', 'place', 'location', 'waypoint'],
        examples: [
            'locatePlace("Buckingham Palace", queryAs: "poi", where: { mode: "within", viewport: true }, waypointIndex: 0)',
            'locatePlace("Tower Bridge", queryAs: "poi", where: { mode: "nearby", viewport: true }, waypointIndex: 1)',
            'locatePlace("Westminster Abbey", queryAs: "poi", where: { mode: "global" })',
            'locatePlace("10 Downing Street", queryAs: "place", where: { mode: "nearby", position: [4.9, 52.37] })',
            'locatePlace("Amsterdam", queryAs: "place", where: { mode: "global" }, entryId: "amsterdam-city", geometry: { show: true })  // outline the city',
            'locatePlace("Utrecht", queryAs: "place", where: { mode: "global" }, entryId: "utrecht-city", geometry: { show: true, mode: "add" })  // also outline a second city',
        ],
        examplePrompts: [
            'Where is the Louvre?',
            'Pin Central Station on the map',
            'What are the coordinates of Times Square?',
            'Set my origin to Schiphol Airport',
            'Outline Amsterdam on the map',
            'Show the boundary of Berlin',
        ],
        relatedTools: ['setRoute', 'addWaypointsToRoute', 'getCurrentWaypoints', 'recallPlaces'],
    },
    reverseGeocode: {
        description: reverseGeocodeDescription,
        classificationPrompt:
            'Convert [lng, lat] coordinates to an address; use after map clicks or any tool that returns a position.',
        inputSchema: reverseGeocodeSchema,
        outputSchema: reverseGeocodeOutputSchema,
        execute: executeReverseGeocode,
        tags: ['location', 'place'],
        examples: ['reverseGeocode({ position: [4.9, 52.4] })'],
        examplePrompts: [
            "What's the address at this point?",
            'Which city is [4.9, 52.4] in?',
            'Name the place where I clicked',
        ],
        relatedTools: ['getViewport', 'getCurrentLocation', 'updatePlacesDisplay', 'locatePlace'],
    },
    discoverPlaces: discoverPlacesBuilder,
    processPlaces: processPlacesBuilder,
    processGeometries: {
        description: processGeometriesDescription,
        classificationPrompt:
            'Aggregate polygons (place footprints, isochrones, custom-entries) via dynamic JS (h3, turf) — union/intersect/buffer/h3 coverage. Output writes a NEW custom-geometries entry.',
        inputSchema: processGeometriesSchema,
        outputSchema: processGeometriesOutputSchema,
        execute: executeProcessGeometries,
        tags: ['geometry', 'boundary', 'aggregation', 'turf', 'h3'],
        examples: [
            'processGeometries({ geometriesEntryIDs: [{ kind: "place", id: "amsterdam-id" }, { kind: "place", id: "rotterdam-id" }], code: "return [turf.union(turf.featureCollection(geometries))].filter(Boolean);", label: "ams ∪ rdam", operation: "union" })',
            'processGeometries({ geometriesEntryIDs: [{ kind: "place", id: "paris-id" }], code: "return [turf.buffer(geometries[0], 5, { units: \'kilometers\' })];", label: "paris +5km", operation: "buffer" })',
            'processGeometries({ geometriesEntryIDs: [{ kind: "places", id: "cities" }], code: "const out = []; for (let i=0;i<geometries.length;i++) for (let j=i+1;j<geometries.length;j++) { const x = turf.intersect(turf.featureCollection([geometries[i], geometries[j]])); if (x) out.push({ ...x, id: `x-${i}-${j}` }); } return out;", label: "pairwise overlaps" })',
            'processGeometries({ geometriesEntryIDs: [{ kind: "ranges", id: "ranges-0" }, { kind: "places", id: "ev-stations" }], code: "const u = geometries.length ? turf.union(turf.featureCollection(geometries)) : null; return u ? [u] : [];", label: "isochrone ∪ ev coverage" })',
            'processGeometries({ geometriesEntryIDs: [{ kind: "place", id: "amsterdam-id" }, { kind: "ranges", id: "ranges-0" }], code: "const outer = geometries.filter(g => g.properties._source.kind === \'place\'); const inner = geometries.filter(g => g.properties._source.kind === \'ranges\'); const env = turf.union(turf.featureCollection(outer)); const u = turf.union(turf.featureCollection(inner)); const inv = (env && u) ? turf.difference(turf.featureCollection([env, u])) : env; return inv ? [{ ...inv, id: \'unreachable\' }] : [];", label: "amsterdam minus reachable", operation: "difference", show: { theme: "inverted", hidePreviousEntries: "all" } })  // areas in Amsterdam NOT reachable from the hospitals — fetch Amsterdam via locatePlace first, then filter by `_source` in code',
        ],
        examplePrompts: [
            'Union the boundaries of these cities',
            'Buffer each neighbourhood by 500 m',
            'Find the overlapping areas of these districts',
            'Compute the h3 hex coverage of these places combined',
            'Combine the reachable area with the EV stations into one zone',
            'Show the areas of Amsterdam not reachable from the hospitals',
        ],
        relatedTools: ['recallGeometries', 'discoverPlaces', 'recallPlaces', 'analyseGeometries'],
        dependsOn: ['discoverPlaces', 'locatePlace', 'findReachableAreas', 'recallGeometries'],
    },
    processRoutes: {
        description: processRoutesDescription,
        classificationPrompt:
            'Dynamic JS over routes → bbox via `routeUtils` → fit camera. Read-only, returns `{ fitOnMap }`. Use when the user wants to focus on a specific PART of a route (worst traffic, toll section, km-10-to-20 segment).',
        inputSchema: processRoutesSchema,
        outputSchema: processRoutesOutputSchema,
        execute: executeProcessRoutes,
        tags: ['route', 'utilities'],
        examples: [
            'processRoutes({ code: "const r = routes.features[0]; const sec = (r.properties.sections.traffic ?? []).slice().sort((a,b) => (b.delayInSeconds ?? 0) - (a.delayInSeconds ?? 0))[0]; const bbox = sec ? routeUtils.getSectionBBox(r, sec) : turf.bbox(r); return { fitOnMap: { bbox, padding: 80 } };" })',
            'processRoutes({ code: "const r = routes.features[0]; const sec = r.properties.sections.toll?.[0]; if (!sec) return { fitOnMap: turf.bbox(r) }; return { fitOnMap: routeUtils.getSectionBBox(r, sec) };" })',
            'processRoutes({ code: "const r = routes.features[0]; const a = routeUtils.getCoordinateAtRouteProgress(r, { traveledDistanceInMeters: 10000 }); const b = routeUtils.getCoordinateAtRouteProgress(r, { traveledDistanceInMeters: 20000 }); if (!a || !b) return { fitOnMap: turf.bbox(r) }; const fc = { type: \'FeatureCollection\', features: [turf.point(a.position), turf.point(b.position)] }; return { fitOnMap: { bbox: turf.bbox(fc), padding: 100 } };" })',
            "processRoutes({ placesEntryIDs: [\"ev-stations\"], code: \"const r = routes.features[0]; const ev = (placesByEntry?.['ev-stations']?.features ?? []).filter(p => turf.pointToLineDistance(p, r, { units: 'meters' }) <= 1000); if (ev.length === 0) return { fitOnMap: turf.bbox(r) }; return { fitOnMap: { bbox: turf.bbox({ type: 'FeatureCollection', features: [...ev, r] }), padding: 80 } };\" })",
        ],
        examplePrompts: [
            'Zoom into the worst traffic on the route',
            'Show me the toll section',
            'Focus on the segment between km 10 and 20',
            'Frame the part of the route inside France',
            'Zoom to the first leg only',
            'Focus on the route plus every EV station within 1 km of it',
        ],
        relatedTools: ['recallRoutes', 'analyseRoutes'],
        dependsOn: ['setRoute', 'recallRoutes', 'recallPlaces'],
    },
    analyseGeometries: {
        description: analyseGeometriesDescription,
        classificationPrompt:
            'Compute aggregate stats / charts over polygons (place footprints, isochrones, custom-entries) via dynamic JS (h3, turf). Result attaches to each contributing places-entry / custom-entry as `_analysis[name]`. `outputFormat`: `json` or `chart`.',
        inputSchema: analyseGeometriesSchema,
        outputSchema: analyseGeometriesOutputSchema,
        execute: executeAnalyseGeometries,
        tags: ['geometry', 'boundary', 'analysis', 'turf', 'h3'],
        examples: [
            'analyseGeometries({ geometriesEntryIDs: [{ kind: "places", id: "cities" }], name: "areas", code: "return geometries.map(f => ({ id: f.id, km2: +(turf.area(f)/1e6).toFixed(2) }));" })',
            'analyseGeometries({ geometriesEntryIDs: [{ kind: "place", id: "amsterdam" }], name: "h3-coverage-8", code: "const cells = new Set(); for (const f of geometries) for (const c of h3.polygonToCells(f.geometry.coordinates, 8)) cells.add(c); return { resolution: 8, cellCount: cells.size };" })',
            'analyseGeometries({ geometriesEntryIDs: [{ kind: "custom", id: "bakery-candidates-gap-oost" }], name: "candidate-area", code: "return { totalKm2: +(geometries.reduce((a,f)=>a+turf.area(f),0)/1e6).toFixed(2) };" })',
            'analyseGeometries({ geometriesEntryIDs: [{ kind: "places", id: "cities" }], name: "area-bar", outputFormat: "chart", code: "return { type: \'bar\', data: { labels: geometries.map(f => f.id), datasets: [{ label: \'km²\', data: geometries.map(f => +(turf.area(f)/1e6).toFixed(2)) }] } };" })',
        ],
        examplePrompts: [
            'How big are these areas?',
            'h3 hex coverage of this neighbourhood',
            'Bar chart of city areas',
            'Combined bbox of these places',
            'How big is the candidate zone we just produced?',
        ],
        relatedTools: ['recallGeometries', 'discoverPlaces', 'recallPlaces', 'processGeometries'],
        dependsOn: ['discoverPlaces', 'locatePlace', 'findReachableAreas', 'recallGeometries'],
    },
    analysePlaces: analysePlacesBuilder,
    analyseRoutes: {
        description: analyseRoutesDescription,
        classificationPrompt:
            'Aggregate / summarise / chart existing routes via dynamic JS (h3, turf). Optionally pass `placesEntryIDs` to cross-reference routes with places (POIs near route, per leg/country). `outputFormat`: `json` or `chart`.',
        inputSchema: analyseRoutesSchema,
        outputSchema: analyseRoutesOutputSchema,
        execute: executeAnalyseRoutes,
        tags: ['route', 'utilities'],
        examples: [
            'analyseRoutes({ name: "summary", code: "return routes.features.map(r => ({ index: r.properties.index, distanceKm: r.properties.summary.lengthInMeters / 1000, durationMin: r.properties.summary.travelTimeInSeconds / 60, trafficDelaySec: r.properties.summary.trafficDelayInSeconds }));" })',
            'analyseRoutes({ name: "delay-by-country", code: "const byCountry = {}; for (const r of routes.features) for (const c of (r.properties.sections.country ?? [])) byCountry[c.countryCodeISO3] = (byCountry[c.countryCodeISO3] ?? 0) + (r.properties.sections.traffic ?? []).filter(t => t.startPointIndex >= c.startPointIndex && t.endPointIndex <= c.endPointIndex).reduce((s, t) => s + (t.delayInSeconds ?? 0), 0); return byCountry;" })',
            'analyseRoutes({ name: "alternative-comparison", outputFormat: "chart", code: "const r = routes.features; return { type: \'bar\', data: { labels: r.map(x => `Route ${x.properties.index}`), datasets: [{ label: \'Travel time (min)\', data: r.map(x => Math.round(x.properties.summary.travelTimeInSeconds / 60)) }, { label: \'Distance (km)\', data: r.map(x => Math.round(x.properties.summary.lengthInMeters / 1000)) }] } };" })',
            'analyseRoutes({ routesEntryIDs: ["routes-0"], name: "hex-coverage-7", code: "const cells = new Set(); for (const r of routes.features) for (const [lng, lat] of r.geometry.coordinates) cells.add(h3.latLngToCell(lat, lng, 7)); return { resolution: 7, cellCount: cells.size, cells: [...cells] };" })',
            'analyseRoutes({ placesEntryIDs: ["ev-stations"], name: "ev-near-route-500m", code: "const route = routes.features[0]; const out = {}; for (const [id, places] of Object.entries(placesByEntry)) out[id] = places.features.filter(p => turf.pointToLineDistance(p, route, { units: \'meters\' }) <= 500).length; return { withinMeters: 500, byEntry: out };" })',
            'analyseRoutes({ placesEntryIDs: ["cafes", "hotels"], name: "stops-per-leg", code: "const route = routes.features[0]; const corridor = turf.buffer(route, 0.3, { units: \'kilometers\' }); const legs = route.properties.sections.leg; return Object.fromEntries(Object.entries(placesByEntry).map(([id, fc]) => [id, legs.map((leg, i) => ({ leg: i, count: fc.features.filter(p => leg.startPointIndex != null && turf.booleanPointInPolygon(p, corridor)).length }))])); " })',
        ],
        examplePrompts: [
            'How long is each route alternative?',
            'Compare the travel times of these route options',
            'Bar chart of distance and time per alternative',
            'Total traffic delay grouped by country',
            'h3 hex coverage of the route at resolution 7',
            'How many EV stations are within 500 m of the route?',
            'Count cafes and hotels per leg of the route',
            'Which POIs from the search are close to the route?',
        ],
        relatedTools: ['recallRoutes', 'recallPlaces', 'setRoute', 'processRoutes', 'discoverPlaces'],
        dependsOn: ['setRoute', 'recallRoutes', 'recallPlaces'],
    },
    setRoute: {
        description: setRouteDescription,
        classificationPrompt:
            'Use to define a new route or change route waypoints/options. Pass `locations` for a new origin/stops/destination, `parameters` to update cost model / alternatives / when, or both together. Do not use to show, query, or modify an existing displayed route.',
        inputSchema: setRouteSchema,
        outputSchema: setRouteOutputSchema,
        execute: executeSetRoute,
        tags: ['route', 'waypoint', 'location'],
        examples: [
            'setRoute({ locations: [{ query: "Amsterdam" }, { query: "Brussels" }] })',
            'setRoute({ locations: [{ query: "Eiffel Tower" }, { query: "Louvre Museum" }, { query: "Notre Dame" }] })',
            'setRoute({ parameters: { maxAlternatives: 2 } })',
            'setRoute({ parameters: { costModel: { routeType: "fast", avoid: ["tollRoads"] } } })',
            'setRoute({ parameters: { when: { option: "departAt", date: "2025-06-01T09:00:00Z" } } })',
            'setRoute({ locations: [{ query: "Paris" }, { query: "Lyon" }], parameters: { costModel: { routeType: "short" } } })',
        ],
        examplePrompts: [
            'Get directions from Paris to Lyon',
            'Route me from Amsterdam to Brussels',
            'Plan a new trip to the airport',
            'Change my origin to Schiphol',
            'Re-route from a different starting point',
            'Avoid toll roads',
            'Find the fastest route',
            'Show 2 alternative routes',
            'Depart at 9am',
        ],
        relatedTools: [
            'updateRoutesDisplay',
            'addWaypointsToRoute',
            'removeWaypointsFromRoute',
            'replaceWaypointInRoute',
            'recallRoutes',
        ],
    },
    addWaypointsToRoute: {
        description: addWaypointsToRouteDescription,
        classificationPrompt:
            'Extend the route by prepending a new origin and/or appending a new destination (preserving the existing endpoints as stops), and/or inserting intermediate stops at optimal positions, then recalculate. Use setRoute when the user wants to fully replace waypoints.',
        inputSchema: addWaypointsToRouteSchema,
        outputSchema: addWaypointsToRouteOutputSchema,
        execute: executeAddWaypointsToRoute,
        tags: ['route', 'waypoint'],
        examples: [
            'addWaypointsToRoute({ stops: [{ query: "Westminster Abbey" }] })  // single intermediate stop',
            'addWaypointsToRoute({ stops: [{ query: "Reims" }, { query: "Metz" }] })  // multiple stops, settle into along-route order',
            'addWaypointsToRoute({ origin: { query: "my house" } })  // prepend new origin; previous origin becomes a stop',
            'addWaypointsToRoute({ destination: { query: "Heathrow Airport" } })  // append new destination; previous destination becomes a stop',
            'addWaypointsToRoute({ origin: { query: "Schiphol" }, destination: { query: "Brussels" } })  // extend on both ends',
            'addWaypointsToRoute({ origin: { query: "X" }, stops: [{ query: "Y" }] })  // combine endpoint extension and stops',
        ],
        examplePrompts: [
            'Add a stop at Westminster Abbey',
            'Add stops at Reims and Metz on the way',
            'Pick me up from my house first, then continue the trip',
            'Continue past the destination to Heathrow',
        ],
        relatedTools: [
            'locatePlace',
            'setRoute',
            'updateRoutesDisplay',
            'removeWaypointsFromRoute',
            'replaceWaypointInRoute',
        ],
        dependsOn: ['setRoute'],
    },
    removeWaypointsFromRoute: {
        description: removeWaypointsFromRouteDescription,
        classificationPrompt: 'Remove one or more waypoints by index from the current route and recalculate.',
        inputSchema: removeWaypointsFromRouteSchema,
        outputSchema: removeWaypointsFromRouteOutputSchema,
        execute: executeRemoveWaypointsFromRoute,
        tags: ['route', 'waypoint'],
        examples: [
            'removeWaypointsFromRoute({ waypointIndices: [1] })  // remove a single stop',
            'removeWaypointsFromRoute({ waypointIndices: [1, 2] })  // remove multiple stops in one call',
        ],
        examplePrompts: [
            'Remove the second stop from my route',
            'Delete the Utrecht stop',
            'Drop the last two intermediate stops',
        ],
        relatedTools: ['addWaypointsToRoute', 'replaceWaypointInRoute', 'setRoute', 'updateRoutesDisplay'],
        dependsOn: ['setRoute'],
    },
    replaceWaypointInRoute: {
        description: replaceWaypointInRouteDescription,
        classificationPrompt:
            "Overwrite a single waypoint of the current route in place — by 'origin', 'destination', or numeric index — and recalculate. Other waypoints are kept.",
        inputSchema: replaceWaypointInRouteSchema,
        outputSchema: replaceWaypointInRouteOutputSchema,
        execute: executeReplaceWaypointInRoute,
        tags: ['route', 'waypoint'],
        examples: [
            'replaceWaypointInRoute({ waypointIndex: "origin", location: { query: "Schiphol" } })',
            'replaceWaypointInRoute({ waypointIndex: "destination", location: { query: "Heathrow" } })',
            'replaceWaypointInRoute({ waypointIndex: 1, location: { query: "Utrecht" } })  // overwrite the first intermediate stop',
        ],
        examplePrompts: [
            'Change the origin to Schiphol',
            'Make Heathrow my destination',
            'Replace the second stop with Utrecht',
        ],
        relatedTools: ['addWaypointsToRoute', 'removeWaypointsFromRoute', 'setRoute', 'locatePlace'],
        dependsOn: ['setRoute'],
    },
    getPOICategoryCodes: {
        description: getPoiCategoryCodesDescription,
        classificationPrompt:
            'Resolve natural-language category names (e.g. "gym", "italian food") to POICategory codes for discoverPlaces.',
        inputSchema: getPoiCategoryCodesSchema,
        outputSchema: getPoiCategoryCodesOutputSchema,
        execute: executeGetPoiCategoryCodes,
        tags: ['discover', 'place'],
        examples: [
            'getPOICategoryCodes()',
            'getPOICategoryCodes(filters: ["gym"])',
            'getPOICategoryCodes(filters: ["italian restaurant"])  // multi-word phrase, spaces removed before matching',
            'getPOICategoryCodes(filters: ["restaurant"], language: "fr-FR")',
        ],
        examplePrompts: ['What POI categories are available?', "What's the code for gym?"],
        relatedTools: ['discoverPlaces', 'togglePOIs'],
    },
    getTrafficIncidents: {
        description: getTrafficIncidentsDescription,
        classificationPrompt:
            'Loader for traffic incidents — caches features in state, renders on the map, returns `{count, entryId}` only. ' +
            'MANDATORY: always also pick startTrafficIncidentsMonitor (no exceptions — they are a pair, data goes stale without it). ' +
            'Also co-pick analyseIncidents (counts / charts / top-N / clusters) and focusIncidents (highlight a subset) when the query implies them.',
        inputSchema: getTrafficIncidentsSchema,
        outputSchema: getTrafficIncidentsOutputSchema,
        execute: executeGetTrafficIncidents,
        tags: ['traffic', 'location'],
        examples: [
            'getTrafficIncidents({ bbox: [4.728, 52.278, 5.080, 52.479] })',
            'getTrafficIncidents({ bbox: [...], categoryFilter: ["accident", "jam"] })',
            'getTrafficIncidents({ bbox: [...], categoryFilter: ["roadworks"], timeValidityFilter: ["future"] })',
        ],
        examplePrompts: ['Fetch traffic incidents in Amsterdam', 'Any accidents in this area?'],
        relatedTools: [
            'calculateBBox',
            'getViewport',
            'analyseIncidents',
            'focusIncidents',
            'startTrafficIncidentsMonitor',
        ],
    },
    analyseIncidents: {
        description: analyseIncidentsDescription,
        classificationPrompt:
            'Aggregate / chart / cluster an incidents entry via dynamic JS (h3, turf). Re-runs on every monitor-tick; ' +
            '`previous` carries the prior result for trend reads. Pick for counts, group-bys, top-N, charts, density, clusters.',
        inputSchema: analyseIncidentsSchema,
        outputSchema: analyseIncidentsOutputSchema,
        execute: executeAnalyseIncidents,
        tags: ['traffic', 'incident', 'analytics', 'state'],
        examples: [
            'analyseIncidents({ name: \'by-category\', code: "const c = {}; for (const i of incidents) c[i.properties.category] = (c[i.properties.category] ?? 0) + 1; return { total: incidents.length, byCategory: c };" })',
            'analyseIncidents({ name: \'top-delays\', code: "return [...incidents].sort((a,b) => (b.properties.delayInSeconds ?? 0) - (a.properties.delayInSeconds ?? 0)).slice(0,5).map(i => ({ id: i.properties.id, delay: i.properties.delayInSeconds, road: i.properties.roadNumbers?.[0] }));" })',
            "analyseIncidents({ name: 'category-bar', outputFormat: 'chart', code: \"const c = {}; for (const i of incidents) c[i.properties.category] = (c[i.properties.category] ?? 0) + 1; const e = Object.entries(c).sort((a,b) => b[1]-a[1]); return { type: 'bar', data: { labels: e.map(x => x[0]), datasets: [{ label: 'Incidents', data: e.map(x => x[1]) }] } };\" })",
        ],
        examplePrompts: [
            'How many incidents of each category?',
            'Top 5 incidents by delay',
            'Total delay grouped by road',
            'Which jams are growing vs fading on this monitored area?',
            'Bar chart of incidents per category',
            'Hex density of incidents at resolution 8',
        ],
        relatedTools: ['getTrafficIncidents', 'focusIncidents'],
        dependsOn: ['getTrafficIncidents'],
    },
    focusIncidents: {
        description: focusIncidentsDescription,
        classificationPrompt:
            'Highlight a subset of incidents on an existing entry (drives map dim/highlight + FocusChip). ' +
            'Pick for "focus on…", "show only…", "highlight the…". Compose with analyseIncidents to compute the ids.',
        inputSchema: focusIncidentsSchema,
        outputSchema: focusIncidentsOutputSchema,
        execute: executeFocusIncidents,
        tags: ['traffic', 'incident', 'state', 'ui'],
        examples: [
            "focusIncidents({ incidentsEntryID: 'incidents-0', incidentIds: ['TTI-...', 'TTI-...'], reason: 'top 3 by delay' })",
        ],
        examplePrompts: [
            'Focus on the 3 worst incidents by delay',
            'Highlight the closures',
            'Show only the incidents on the A4',
        ],
        relatedTools: ['analyseIncidents', 'getTrafficIncidents'],
        dependsOn: ['getTrafficIncidents'],
    },
    startTrafficIncidentsMonitor: {
        description: startTrafficIncidentsMonitorDescription,
        classificationPrompt:
            'Polls an existing incidents entry on a fixed interval (default 60s); registered analyses re-run on each tick. ' +
            'ALWAYS pick this whenever getTrafficIncidents is picked — they are a mandatory pair, no exceptions. ' +
            'Without it the loaded data is a frozen snapshot. Also pick on its own when the user says ' +
            '"live"/"watch"/"keep updated"/"refresh every N seconds" against an already-loaded entry.',
        inputSchema: startTrafficIncidentsMonitorSchema,
        outputSchema: startTrafficIncidentsMonitorOutputSchema,
        execute: executeStartTrafficIncidentsMonitor,
        tags: ['traffic', 'incident', 'state'],
        examples: [
            "startTrafficIncidentsMonitor({ incidentsEntryID: 'incidents-0' })",
            "startTrafficIncidentsMonitor({ incidentsEntryID: 'incidents-0', intervalMs: 30000 })",
        ],
        examplePrompts: [
            'Keep this updated',
            'Refresh the incidents every 30 seconds',
            'Watch this area for new accidents',
        ],
        relatedTools: ['getTrafficIncidents', 'stopTrafficIncidentsMonitor', 'analyseIncidents'],
        dependsOn: ['getTrafficIncidents'],
    },
    stopTrafficIncidentsMonitor: {
        description: stopTrafficIncidentsMonitorDescription,
        classificationPrompt:
            'Stop polling an incidents entry; the entry stays in state with its last data. ' +
            'Pick for "stop refreshing"/"pause updates" or when ending a watch.',
        inputSchema: stopTrafficIncidentsMonitorSchema,
        outputSchema: stopTrafficIncidentsMonitorOutputSchema,
        execute: executeStopTrafficIncidentsMonitor,
        tags: ['traffic', 'incident', 'state'],
        examples: ["stopTrafficIncidentsMonitor({ incidentsEntryID: 'incidents-0' })"],
        examplePrompts: ['Stop refreshing', 'Pause updates for this area'],
        relatedTools: ['startTrafficIncidentsMonitor', 'getTrafficIncidents'],
        dependsOn: ['startTrafficIncidentsMonitor'],
    },
    getTrafficAreaAnalytics: {
        description: getTrafficAreaAnalyticsDescription,
        classificationPrompt:
            'Fetch historical traffic analytics (speed, congestion, travel time) for an area. queryTrafficAnalytics drills down without re-fetching.',
        inputSchema: getTrafficAreaAnalyticsSchema,
        outputSchema: getTrafficAreaAnalyticsOutputSchema,
        execute: executeGetTrafficAreaAnalytics,
        tags: ['traffic', 'location'],
        examples: [
            "getTrafficAreaAnalytics({ bbox: [4.728, 52.278, 5.080, 52.479], metrics: ['speed', 'congestionLevel'], startDate: '2025-03-01', endDate: '2025-03-07' })",
            "getTrafficAreaAnalytics({ bbox: [...], metrics: ['congestionLevel'], hours: [7,8,9,17,18] })",
        ],
        examplePrompts: [
            'What was the average congestion in Amsterdam last week?',
            'Analyze traffic patterns during rush hour in this area',
            'Show me historical speed data for the city center',
        ],
        relatedTools: ['queryTrafficAnalytics', 'showTrafficAreaAnalytics', 'calculateBBox', 'getViewport'],
        dependsOn: ['locatePlace'],
    },
    queryTrafficAnalytics: {
        description: queryTrafficAnalyticsDescription,
        classificationPrompt:
            'Query cached traffic analytics data or check what metric/mode is currently displayed on the map.',
        inputSchema: queryTrafficAnalyticsSchema,
        outputSchema: queryTrafficAnalyticsOutputSchema,
        execute: executeQueryTrafficAnalytics,
        tags: ['traffic', 'location'],
        examples: [
            "queryTrafficAnalytics({ granularity: 'daily' })",
            "queryTrafficAnalytics({ granularity: 'hourly', hourStart: 7, hourEnd: 9, metric: 'congestionLevel' })",
            "queryTrafficAnalytics({ granularity: 'average', dayOfWeek: [6, 7] })",
        ],
        // NOTE: "What am I looking at?" awareness should be handled at a higher level
        // (e.g. system prompt or state summary injected into context), not per-tool examplePrompts.
        // Current approach works but doesn't scale — every stateful tool would need similar hints.
        examplePrompts: [
            'Show me the daily breakdown',
            'What was rush hour congestion?',
            'Which day had the worst traffic?',
            'What metric am I looking at?',
            'What is currently shown on the map?',
        ],
        relatedTools: ['getTrafficAreaAnalytics', 'showTrafficAreaAnalytics'],
        dependsOn: ['getTrafficAreaAnalytics'],
    },
    updatePlacesDisplay: {
        description: updatePlacesDisplayDescription,
        classificationPrompt:
            'Show, hide, and swap places entries on the map — add some (as pins and/or boundary polygons), remove others, swap atomically, or render boundaries.',
        inputSchema: updatePlacesDisplaySchema,
        outputSchema: updatePlacesDisplayOutputSchema,
        execute: executeUpdatePlacesDisplay,
        tags: ['place', 'location', 'map style', 'boundary', 'outline'],
        examples: [
            'updatePlacesDisplay({ add: ["places-2"] })',
            'updatePlacesDisplay({ add: ["places-1", "places-3"], markerType: "base-map" })',
            'updatePlacesDisplay({ remove: ["places-1"] })',
            'updatePlacesDisplay({ removeMatching: ["cinema"] })  // hide every entry labelled "cinema"',
            'updatePlacesDisplay({ addMatching: ["cafe"] })',
            'updatePlacesDisplay({ clear: true })',
            'updatePlacesDisplay({ clear: true, add: ["places-2"] })  // atomic swap: hide everything, show this',
            'updatePlacesDisplay({ markerType: "pin" })  // re-pin the most recently stored entry',
            'updatePlacesDisplay({ geometry: {} })  // outline the most recently stored entry',
            'updatePlacesDisplay({ add: ["places-2"], geometry: { mode: "add" } })  // also outline on top of existing boundaries',
            'updatePlacesDisplay({ add: ["places-2"], markerType: "pin", geometry: { theme: "outline" } })  // pin AND outline',
            'updatePlacesDisplay({ add: ["places-2"], geometry: { placeIds: ["G55fc4abe-..."], theme: "outline" } })  // outline a subset',
        ],
        examplePrompts: [
            'Show the results on the map',
            'Pin the search results',
            'Hide the banks',
            'Also show the cafes on the map',
            'Additionally pin the pubs',
            'Remove the banks from the map',
            'Drop every entry labelled "parking" from the map',
            'Toggle off the hotels without clearing the rest',
            'Replace the pins with the new set',
            'Show entry places-3 as base-map POIs',
            'Show the boundary of Amsterdam on the map',
            'Outline these neighbourhoods',
            'Highlight the shape of this place',
            'Pin the cities and outline them too',
            'Also outline Utrecht while keeping Amsterdam drawn',
            'Add the neighbourhood boundaries on top of the pins',
        ],
        relatedTools: ['discoverPlaces', 'locatePlace', 'reverseGeocode', 'recallPlaces', 'clearMap', 'flyTo'],
        dependsOn: ['discoverPlaces', 'locatePlace', 'processPlaces'],
    },
    updateRoutesDisplay: {
        description: updateRoutesDisplayDescription,
        classificationPrompt:
            'Show, hide, and swap routes entries on the map — add some, remove others, swap atomically, or switch the highlighted alternative.',
        inputSchema: updateRoutesDisplaySchema,
        outputSchema: updateRoutesDisplayOutputSchema,
        execute: executeUpdateRoutesDisplay,
        tags: ['route', 'waypoint'],
        examples: [
            'updateRoutesDisplay({ add: ["routes-1"] })',
            'updateRoutesDisplay({ add: ["routes-0", "routes-2"] })',
            'updateRoutesDisplay({ remove: ["routes-1"] })',
            'updateRoutesDisplay({ removeMatching: ["Brussels"] })  // hide every entry whose label mentions "Brussels"',
            'updateRoutesDisplay({ addMatching: ["Edinburgh"] })',
            'updateRoutesDisplay({ clear: true })',
            'updateRoutesDisplay({ clear: true, add: ["routes-2"] })  // atomic swap: hide everything, show this',
            'updateRoutesDisplay({ selectedIndex: 1 })  // re-highlight alternative #1 on the most recent route',
            'updateRoutesDisplay({ add: ["routes-0"], selectedIndex: 2, fitBounds: false })',
        ],
        examplePrompts: [
            'Draw the route on the map',
            'Show the directions',
            'Display the calculated route',
            'Show the Edinburgh route from earlier',
            'Also show the Brussels route',
            'Hide the Lyon route',
            'Switch to the second alternative',
            'Highlight alternative 2',
            'Replace what is shown with this route',
        ],
        relatedTools: ['setRoute', 'processRoutes', 'recallRoutes', 'clearMap'],
        dependsOn: ['setRoute'],
    },
    showTrafficAreaAnalytics: {
        description: showTrafficAreaAnalyticsDescription,
        classificationPrompt:
            'Render traffic analytics as hexgrid, heatmap, or tiles with custom colors, filtering, height, and tooltip.',
        inputSchema: showTrafficAreaAnalyticsSchema,
        outputSchema: showTrafficAreaAnalyticsOutputSchema,
        execute: executeShowTrafficAreaAnalytics,
        tags: ['traffic', 'map style'],
        examples: [
            'showTrafficAreaAnalytics()',
            "showTrafficAreaAnalytics({ mode: 'hexgrid-2d', metric: 'speed', colorTheme: 'heat' })",
            'showTrafficAreaAnalytics({ filter: { min: 50 } })',
            "showTrafficAreaAnalytics({ scaleMode: 'currentRange', heightScale: 200 })",
            'showTrafficAreaAnalytics({ visible: false })',
        ],
        examplePrompts: [
            'Show it on the map',
            'Visualize the congestion',
            'Only show areas with congestion above 50%',
            'Normalize height to the current data range',
            'Switch to heatmap view',
        ],
        relatedTools: ['getTrafficAreaAnalytics', 'queryTrafficAnalytics', 'toggleTrafficFlow', 'clearMap'],
        dependsOn: ['getTrafficAreaAnalytics'],
    },
    showWaypoints: {
        description: showWaypointsDescription,
        classificationPrompt: 'Display staged origin/stop/destination markers without drawing the route line.',
        inputSchema: showWaypointsSchema,
        outputSchema: showWaypointsOutputSchema,
        execute: executeShowWaypoints,
        tags: ['waypoint', 'route'],
        examples: ['showWaypoints()'],
        examplePrompts: ['Show the waypoints on the map', 'Mark my route stops'],
        relatedTools: ['setRoute', 'updateRoutesDisplay', 'getShownWaypoints', 'clearMap'],
        dependsOn: ['setRoute', 'locatePlace'],
    },
    getShownPlaces: {
        description: getShownPlacesDescription,
        classificationPrompt:
            'Return places currently displayed on the map (available after updatePlacesDisplay or locatePlace).',
        inputSchema: getShownPlacesSchema,
        outputSchema: getShownPlacesOutputSchema,
        execute: executeGetShownPlaces,
        tags: ['place', 'location'],
        examples: ['getShownPlaces()'],
        examplePrompts: [
            'What places are on the map?',
            'Which of my search results are currently displayed?',
            'How many places are visible right now?',
        ],
        relatedTools: ['updatePlacesDisplay', 'clearMap', 'locatePlace', 'reverseGeocode'],
        dependsOn: ['updatePlacesDisplay'],
    },
    getShownRoutes: {
        description: getShownRoutesDescription,
        classificationPrompt: 'Return routes currently rendered on the map (available after updateRoutesDisplay).',
        inputSchema: getShownRoutesSchema,
        outputSchema: getShownRoutesOutputSchema,
        execute: executeGetShownRoutes,
        tags: ['route'],
        examples: ['getShownRoutes()'],
        examplePrompts: ['What routes are displayed?', 'Is there a route on the map?'],
        relatedTools: ['updateRoutesDisplay', 'clearMap'],
        dependsOn: ['updateRoutesDisplay'],
    },
    getShownWaypoints: {
        description: getShownWaypointsDescription,
        classificationPrompt:
            'Return waypoint markers currently shown on the map (available after updateRoutesDisplay or showWaypoints).',
        inputSchema: getShownWaypointsSchema,
        outputSchema: getShownWaypointsOutputSchema,
        execute: executeGetShownWaypoints,
        tags: ['waypoint', 'route'],
        examples: ['getShownWaypoints()'],
        examplePrompts: ['What waypoints are shown?', 'List the stops on the map'],
        relatedTools: ['updateRoutesDisplay', 'clearMap'],
        dependsOn: ['updateRoutesDisplay', 'showWaypoints'],
    },
    getShownRouteTrafficIncidents: {
        description: getShownRouteTrafficIncidentsDescription,
        classificationPrompt: 'Return traffic incidents overlaid on the shown route.',
        inputSchema: getShownRouteTrafficIncidentsSchema,
        outputSchema: getShownRouteTrafficIncidentsOutputSchema,
        execute: executeGetShownRouteTrafficIncidents,
        tags: ['traffic', 'route'],
        examples: ['getShownRouteTrafficIncidents()'],
        examplePrompts: ['What traffic incidents are on my route?', 'Any delays along the route?'],
        relatedTools: ['updateRoutesDisplay', 'clearMap', 'setRoute'],
        dependsOn: ['updateRoutesDisplay'],
    },
    getShownIncidents: {
        description: getShownIncidentsDescription,
        classificationPrompt:
            'Return real-time incidents currently visible in the map viewport (rendered on map, not fetched from service).',
        inputSchema: getShownIncidentsSchema,
        outputSchema: getShownIncidentsOutputSchema,
        execute: executeGetShownIncidents,
        tags: ['traffic', 'location'],
        examples: ['getShownIncidents()'],
        examplePrompts: ['What traffic incidents are visible?', 'Any incidents in the current view?'],
        relatedTools: ['toggleTrafficIncidents', 'flyTo', 'getViewport'],
        dependsOn: ['toggleTrafficIncidents'],
    },
    clearMap: {
        description: clearMapDescription,
        classificationPrompt: 'Remove displayed places, routes, or all features from the map.',
        inputSchema: clearMapSchema,
        outputSchema: clearMapOutputSchema,
        execute: executeClearMap,
        tags: ['place', 'route', 'map style'],
        examples: ['clearMap()', 'clearMap(["places"])', 'clearMap(["places", "routes"])'],
        examplePrompts: ['Clear the map', 'Remove all markers', 'Start fresh'],
        relatedTools: ['updatePlacesDisplay', 'updateRoutesDisplay'],
    },
    flyTo: {
        description: flyToDescription,
        classificationPrompt:
            'Move the camera to a bounding box or specific position; use after locating places or computing bounds.',
        inputSchema: flyToSchema,
        outputSchema: flyToOutputSchema,
        execute: executeFlyTo,
        tags: ['location', 'map style'],
        examples: [
            'flyTo({ where: { boundingBox: [4.8, 52.3, 5.0, 52.5] } })',
            'flyTo({ where: { boundingBox: [4.8, 52.3, 5.0, 52.5], padding: 100 } })',
            'flyTo({ where: { position: [4.9, 52.4], zoom: 14 } })',
        ],
        examplePrompts: ['Go to Berlin', 'Center the map on Rome', 'Fly to these coordinates'],
        relatedTools: ['getViewport', 'locatePlace', 'updatePlacesDisplay', 'updateRoutesDisplay', 'calculateBBox'],
    },
    getViewport: {
        description: getViewportDescription,
        classificationPrompt:
            'Return the map center, zoom, and bounding box; use for area-relative queries like "in this area" or "near the map center".',
        inputSchema: getViewportSchema,
        outputSchema: getViewportOutputSchema,
        execute: executeGetViewport,
        tags: ['location', 'map style'],
        examples: ['getViewport()'],
        examplePrompts: [
            'Where is the map centered?',
            "What's the current map area?",
            'What are the current map bounds?',
        ],
        relatedTools: ['locatePlace', 'flyTo', 'discoverPlaces', 'reverseGeocode', 'getTrafficIncidents'],
    },
    recallGeometries: {
        description: recallGeometriesDescription,
        classificationPrompt:
            'List/inspect every polygon source in state across places footprints, ranges isochrones, and custom-geometries entries. Returns tagged ids (`{ kind, id }`) the geometry tools accept.',
        inputSchema: recallGeometriesSchema,
        outputSchema: recallGeometriesOutputSchema,
        execute: executeRecallGeometries,
        tags: ['geometry', 'boundary'],
        examples: [
            'recallGeometries()',
            'recallGeometries({ id: { kind: "places", id: "ev-stations-oost" } })',
            'recallGeometries({ id: { kind: "custom", id: "bakery-candidates-gap-oost" } })',
        ],
        examplePrompts: [
            'What polygons are in state right now?',
            'Which IDs can I pass to processGeometries?',
            'Recall the custom zone we just produced',
            'What does the bakery-candidates entry contain?',
        ],
        relatedTools: ['processGeometries', 'analyseGeometries', 'recallPlaces', 'recallRanges'],
    },
    recallPlaces: recallPlacesBuilder,
    recallRoutes: {
        description: recallRoutesDescription,
        classificationPrompt: 'Return previously calculated routes from this session.',
        inputSchema: recallRoutesSchema,
        outputSchema: recallRoutesOutputSchema,
        execute: executeRecallRoutes,
        tags: ['route'],
        examples: ['recallRoutes()', 'recallRoutes({ id: "routes-0" })'],
        examplePrompts: [
            'What routes have I calculated?',
            'Show the first route we planned',
            'What was the route to Schiphol?',
        ],
        relatedTools: ['setRoute', 'updateRoutesDisplay', 'getCurrentWaypoints'],
        dependsOn: ['setRoute'],
    },
    getCurrentWaypoints: {
        description: getCurrentWaypointsDescription,
        classificationPrompt:
            'Return the staged waypoint slots (origin, stops, destination) not yet committed to a route.',
        inputSchema: getCurrentWaypointsSchema,
        outputSchema: getCurrentWaypointsOutputSchema,
        execute: executeGetCurrentWaypoints,
        tags: ['waypoint', 'route'],
        examples: [
            'getCurrentWaypoints()',
            'getCurrentWaypoints({ slotIndex: 1 })',
            'getCurrentWaypoints({ includeEmptySlots: true })',
            'getCurrentWaypoints({ offset: 2, limit: 4 })',
        ],
        examplePrompts: ['What are my current route waypoints?', "What's my destination?", 'Show my staged stops'],
        relatedTools: ['locatePlace', 'setRoute', 'showWaypoints', 'recallRoutes'],
    },
    getStandardMapStyles: {
        description: getStandardMapStylesDescription,
        classificationPrompt: 'List available standard map style IDs for use with setMapStandardStyle.',
        inputSchema: getStandardMapStylesSchema,
        outputSchema: getStandardMapStylesOutputSchema,
        execute: executeGetStandardMapStyles,
        tags: ['map style'],
        examples: ['getStandardMapStyles()'],
        examplePrompts: ['What map styles are available?', 'List the map themes'],
        relatedTools: ['setMapStandardStyle'],
    },
    setMapStandardStyle: {
        description: setMapStandardStyleDescription,
        classificationPrompt: 'Switch the map to a standard style preset (light, dark, satellite, driving, etc.).',
        inputSchema: setMapStandardStyleSchema,
        outputSchema: setMapStandardStyleOutputSchema,
        execute: executeSetMapStandardStyle,
        tags: ['map style'],
        examples: ['setMapStandardStyle("standardDark")', 'setMapStandardStyle("satellite")'],
        examplePrompts: ['Switch to dark mode', 'Use the satellite view', 'Change to the light theme'],
        relatedTools: ['getStandardMapStyles', 'setLanguage', 'toggleBaseMapLayerGroups', 'getMapStyleLayers'],
    },
    setRouteTheme: {
        description: setRouteThemeDescription,
        classificationPrompt:
            'Color the route line and waypoint icons; prefer over setPaintProperties for route styling.',
        inputSchema: setRouteThemeSchema,
        outputSchema: setRouteThemeOutputSchema,
        execute: executeSetRouteTheme,
        tags: ['route', 'map style'],
        examples: [
            'setRouteTheme({ mainColor: "#FF0000" })  // red route',
            'setRouteTheme({ mainColor: "coral" })',
            'setRouteTheme({ mainColor: "steelblue" })',
        ],
        examplePrompts: ['Make the route line red', 'Change the route color to blue', 'Style the route in coral'],
        relatedTools: ['updateRoutesDisplay', 'setRoute', 'setPaintProperties'],
        dependsOn: ['updateRoutesDisplay'],
    },
    setLanguage: {
        description: setLanguageDescription,
        classificationPrompt: 'Change the language for map labels and all subsequent service API responses.',
        inputSchema: setLanguageSchema,
        outputSchema: setLanguageOutputSchema,
        execute: executeSetLanguage,
        tags: ['map style'],
        examples: ['setLanguage("fr-FR")', 'setLanguage("de-DE")'],
        examplePrompts: ['Show map labels in French', 'Switch the map to German', 'Use Spanish for place names'],
        relatedTools: ['setMapStandardStyle'],
    },
    toggleBaseMapLayerGroups: {
        description: toggleBaseMapLayerGroupsDescription,
        classificationPrompt:
            'Show or hide named base map layer groups (buildings3D, roadLabels, water, placeLabels, etc.).',
        inputSchema: toggleBaseMapLayerGroupsSchema,
        outputSchema: toggleBaseMapLayerGroupsOutputSchema,
        execute: executeToggleBaseMapLayerGroups,
        tags: ['map style'],
        examples: [
            'toggleBaseMapLayerGroups(false, ["buildings3D"])',
            'toggleBaseMapLayerGroups(true, ["roadLabels"])',
        ],
        examplePrompts: ['Hide 3D buildings', 'Show road labels', 'Toggle the building layer'],
        relatedTools: ['togglePOIs', 'getMapStyleLayers', 'setMapStandardStyle'],
    },
    togglePOIs: {
        description: togglePOIsDescription,
        classificationPrompt: 'Show or hide built-in map POI icons with optional category filtering.',
        inputSchema: togglePOIsSchema,
        outputSchema: togglePOIsOutputSchema,
        execute: executeTogglePOIs,
        tags: ['place', 'map style'],
        examples: [
            'togglePOIs({ allMapPOIsVisible: false })',
            'togglePOIs({ allMapPOIsVisible: true, filterCategories: { show: "only", values: ["RESTAURANT", "CAFE"] } })',
            'togglePOIs({ filterCategories: { show: "all_except", values: ["PARKING_GARAGE"] } })',
            'togglePOIs({ reset: true })',
        ],
        examplePrompts: ['Hide all POI icons', 'Show only restaurant POIs', 'Turn off parking icons'],
        relatedTools: ['toggleBaseMapLayerGroups', 'discoverPlaces', 'setMapStandardStyle'],
    },
    toggleTrafficFlow: {
        description: toggleTrafficFlowDescription,
        classificationPrompt:
            'Toggle REAL-TIME traffic flow (colored road segments for live speeds). Not historical analytics.',
        inputSchema: toggleTrafficFlowSchema,
        outputSchema: toggleTrafficFlowOutputSchema,
        execute: executeToggleTrafficFlow,
        tags: ['traffic', 'map style'],
        examples: ['toggleTrafficFlow(true)', 'toggleTrafficFlow(false)'],
        examplePrompts: ['Show traffic flow', 'Turn off traffic colors', 'Enable the congestion overlay'],
        relatedTools: ['toggleTrafficIncidents', 'setRoute', 'getTrafficIncidents'],
    },
    toggleTrafficIncidents: {
        description: toggleTrafficIncidentsDescription,
        classificationPrompt:
            'Toggle REAL-TIME traffic incident markers and lines (accidents, jams, closures). Not historical analytics.',
        inputSchema: toggleTrafficIncidentsSchema,
        outputSchema: toggleTrafficIncidentsOutputSchema,
        execute: executeToggleTrafficIncidents,
        tags: ['traffic', 'map style'],
        examples: ['toggleTrafficIncidents(true)', 'toggleTrafficIncidents(false)'],
        examplePrompts: ['Show traffic incidents', 'Hide accident icons', 'Enable incident markers'],
        relatedTools: ['toggleTrafficFlow', 'getTrafficIncidents', 'getShownIncidents', 'setRoute'],
    },
    getMapStyleLayers: {
        description: getMapStyleLayersDescription,
        classificationPrompt: 'List MapLibre layer IDs with their paint/layout properties for custom styling.',
        inputSchema: getMapStyleLayersSchema,
        outputSchema: getMapStyleLayersOutputSchema,
        execute: executeGetMapStyleLayers,
        tags: ['map style'],
        examples: ['getMapStyleLayers()', 'getMapStyleLayers("road")', 'getMapStyleLayers("water")'],
        examplePrompts: ['What are the paint properties of the water layer?', 'Show me the road layer layout'],
        relatedTools: ['setLayoutProperties', 'setPaintProperties'],
    },
    setLayoutProperties: {
        description: setLayoutPropertiesDescription,
        classificationPrompt: 'Set MapLibre layout properties (visibility, text-field, icon-size) on named layers.',
        inputSchema: setLayoutPropertiesSchema,
        outputSchema: setLayoutPropertiesOutputSchema,
        execute: executeSetLayoutProperties,
        tags: ['map style'],
        examples: [
            'setLayoutProperties([{ layerId: "road-label", propertyName: "visibility", value: "none" }])',
            'setLayoutProperties([{ layerId: "poi-label", propertyName: "text-field", value: "{name}" }, { layerId: "poi-label", propertyName: "icon-size", value: 1.2 }])',
        ],
        examplePrompts: [
            'Hide the road-label layer',
            'Change the text size on building labels',
            'Make the city labels bigger',
        ],
        relatedTools: ['getMapStyleLayers', 'setPaintProperties'],
        dependsOn: ['getMapStyleLayers'],
    },
    setPaintProperties: {
        description: setPaintPropertiesDescription,
        classificationPrompt: 'Set MapLibre paint properties (colors, widths, opacity) on named layers.',
        inputSchema: setPaintPropertiesSchema,
        outputSchema: setPaintPropertiesOutputSchema,
        execute: executeSetPaintProperties,
        tags: ['map style'],
        examples: [
            'setPaintProperties([{ layerId: "water", propertyName: "fill-color", value: "#0000ff" }])',
            'setPaintProperties([{ layerId: "road", propertyName: "line-color", value: "#ff0000" }, { layerId: "road", propertyName: "line-width", value: 3 }])',
        ],
        examplePrompts: [
            'Make the water bright blue',
            'Change the road color to red',
            'Make buildings semi-transparent',
            'Make the country borders pink',
        ],
        relatedTools: ['getMapStyleLayers', 'setLayoutProperties', 'setRouteTheme'],
        dependsOn: ['getMapStyleLayers'],
    },
    setPitchBearing: {
        description: setPitchBearingDescription,
        classificationPrompt: 'Tilt (pitch) and/or rotate (bearing) the map camera for a 3D perspective.',
        inputSchema: setPitchBearingSchema,
        outputSchema: setPitchBearingOutputSchema,
        execute: executeSetPitchBearing,
        tags: ['map style'],
        examples: [
            'setPitchBearing({ pitch: 45 })',
            'setPitchBearing({ bearing: 90 })',
            'setPitchBearing({ pitch: 60, bearing: -45 })',
        ],
        examplePrompts: ['Tilt the map to 45 degrees', 'Rotate the map to face north', 'Set a 3D perspective view'],
        relatedTools: ['getViewport', 'locatePlace', 'flyTo'],
    },
    zoomInOrOut: {
        description: zoomInOrOutDescription,
        classificationPrompt: 'Adjust the map zoom level by a delta; positive zooms in, negative zooms out.',
        inputSchema: zoomInOrOutSchema,
        outputSchema: zoomInOrOutOutputSchema,
        execute: executeZoomInOrOut,
        tags: ['map style'],
        examples: ['zoomInOrOut({ delta: 2 })', 'zoomInOrOut({ delta: -1 })'],
        examplePrompts: ['Zoom in', 'Zoom out 2 levels', 'Get a wider view'],
        relatedTools: ['getViewport', 'flyTo'],
    },
    executeMaplibreCode: {
        description: executeMaplibreCodeDescription,
        classificationPrompt:
            'Execute any MapLibre JS code against the live map for maximum flexibility — use when no other tool covers the required operation.',
        inputSchema: executeMaplibreCodeSchema,
        outputSchema: executeMaplibreCodeOutputSchema,
        execute: executeExecuteMaplibreCode,
        tags: ['map style', 'maplibre', 'layers', 'sources', 'animation'],
        examples: [
            "executeMaplibreCode({ code: \"map.addSource('pts', { type: 'geojson', data: fc }); map.addLayer({ id: 'pts', type: 'circle', source: 'pts', paint: { 'circle-color': '#f00' } })\" })",
            'executeMaplibreCode({ code: "map.easeTo({ center: [4.9, 52.37], zoom: 14, duration: 2000 })" })',
            "executeMaplibreCode({ code: \"for (let i = 0; i <= 20; i++) { map.setPaintProperty('fill', 'fill-opacity', i / 20); await new Promise(r => setTimeout(r, 50)); }\" })",
            "executeMaplibreCode({ code: \"map.setFog({ color: 'white', 'horizon-blend': 0.1 })\" })",
        ],
        examplePrompts: [
            'Add a GeoJSON layer to the map',
            'Animate the map camera',
            'Fade in a layer gradually',
            'Set map fog or atmosphere',
            'Add a raster tile overlay',
        ],
        relatedTools: ['getMapStyleLayers', 'setLayoutProperties', 'setPaintProperties', 'flyTo'],
        dependsOn: ['getMapStyleLayers'],
    },
    calculateBBox: {
        description: calculateBBoxDescription,
        classificationPrompt:
            'Compute a [minLng, minLat, maxLng, maxLat] bounding box from GeoJSON features or tool results.',
        inputSchema: calculateBBoxSchema,
        execute: executeCalculateBBox,
        tags: ['utilities', 'location'],
        examples: ['calculateBBox(place)', 'calculateBBox(routes)', 'calculateBBox([place1, place2])'],
        examplePrompts: ["What's the bounding box of these places?", 'Calculate the extent of this route'],
        relatedTools: ['flyTo', 'getViewport', 'updatePlacesDisplay', 'updateRoutesDisplay'],
    },
    formatDistance: {
        description: formatDistanceDescription,
        classificationPrompt:
            'Format meters into a human-readable string (e.g. "2.5 km"); use after tools that return distances.',
        inputSchema: formatDistanceSchema,
        execute: executeFormatDistance,
        tags: ['utilities', 'route'],
        examples: ['formatDistance(2500)', 'formatDistance(5000, "imperial_us")'],
        examplePrompts: ['Format 5000 meters as a distance', 'Convert meters to a readable string'],
        relatedTools: ['formatDuration', 'setRoute'],
    },
    formatDuration: {
        description: formatDurationDescription,
        classificationPrompt:
            'Format seconds into a human-readable string (e.g. "1 h 30 min"); use after tools that return durations.',
        inputSchema: formatDurationSchema,
        execute: executeFormatDuration,
        tags: ['utilities', 'route'],
        examples: ['formatDuration(3600)', 'formatDuration(9000)'],
        examplePrompts: ['Format 3600 seconds as a duration', 'Convert seconds to hours and minutes'],
        relatedTools: ['formatDistance', 'setRoute'],
    },
    getCurrentLocation: {
        description: getCurrentLocationDescription,
        classificationPrompt:
            'Get the user\'s physical GPS location from the browser; use for "near me" queries, not map center.',
        inputSchema: getCurrentLocationSchema,
        outputSchema: getCurrentLocationOutputSchema,
        execute: executeGetCurrentLocation,
        tags: ['utilities', 'location'],
        examples: ['getCurrentLocation()'],
        examplePrompts: ['Where am I?', 'Get my GPS location', 'Use my current position'],
        relatedTools: ['discoverPlaces', 'reverseGeocode', 'locatePlace'],
    },
    help: {
        description: helpDescription,
        classificationPrompt:
            'Return available capabilities in summary or searchable detail mode; call when the user asks what you can do.',
        inputSchema: helpSchema,
        outputSchema: helpOutputSchema,
        execute: async () => {
            throw new Error('help tool requires setupTools() — it needs resolved metadata from all tools.');
        },
        tags: ['utilities'],
        examples: [
            'help({ mode: "summary" })',
            'help({ mode: "detail", query: "traffic" })',
            'help({ mode: "detail", tag: "route" })',
            'help({ mode: "detail", query: "route", tag: "utilities" })',
        ],
        examplePrompts: ['What can you do?', 'Show me available tools', 'How do I search for places?'],
    },
    findReachableAreas: {
        description: findReachableAreasDescription,
        classificationPrompt:
            'Calculate isochrone/isodistance polygons showing how far you can travel from one or more origins.',
        inputSchema: findReachableAreasSchema,
        outputSchema: findReachableAreasOutputSchema,
        execute: executeFindReachableAreas,
        tags: ['reachable-range', 'isochrone', 'range', 'EV', 'coverage', 'multi-origin'],
        examples: [
            'findReachableAreas({ origins: [{ query: "Amsterdam", queryAs: "place" }], budgets: [{ type: "timeMinutes", value: 30 }], showOnMap: true })',
            'findReachableAreas({ origins: [{ query: "Amsterdam", queryAs: "place" }, { query: "Rotterdam", queryAs: "place" }], budgets: [{ type: "timeMinutes", value: 30 }], showOnMap: true })',
            'findReachableAreas({ origins: [{ position: { lng: 4.9, lat: 52.3 } }], budgets: [{ type: "timeMinutes", value: 10 }, { type: "timeMinutes", value: 30 }], showOnMap: true, theme: "inverted" })',
            'findReachableAreas({ origins: [{ query: "my location", queryAs: "place" }], budgets: [{ type: "distanceKM", value: 50 }], showOnMap: false })',
        ],
        examplePrompts: [
            'Show me where I can reach in 30 minutes from Amsterdam',
            'Compare 30-minute reach from Amsterdam, Rotterdam and Utrecht',
            'What area is within 50 km of Berlin?',
            'Show 10, 20, 30 minute drive zones from here',
        ],
        relatedTools: ['recallRanges', 'locatePlace'],
    },
    recallRanges: {
        description: recallRangesDescription,
        classificationPrompt: 'Retrieve stored reachable range results from session history.',
        inputSchema: recallRangesSchema,
        outputSchema: recallRangesOutputSchema,
        execute: executeRecallRanges,
        tags: ['recall', 'reachable-range', 'state'],
        examples: ['recallRanges()', 'recallRanges({ id: "ranges-0" })'],
        examplePrompts: ['What range did I calculate earlier?', 'Recall the isochrone from Amsterdam'],
        relatedTools: ['findReachableAreas'],
    },
    recallState: {
        description: recallStateDescription,
        classificationPrompt:
            "Inventory the agent's session: list every places / routes / ranges entry by id+label, plus current map style and POIs/traffic visualization configs.",
        inputSchema: recallStateSchema,
        outputSchema: recallStateOutputSchema,
        execute: executeRecallState,
        tags: ['recall', 'state', 'overview'],
        examples: ['recallState()'],
        examplePrompts: [
            'What do you have so far?',
            'List everything you remember from this session',
            'Show me the current map / data overview',
        ],
        relatedTools: ['recallPlaces', 'recallRoutes', 'recallRanges', 'resetState'],
    },
    resetState: {
        description: resetStateDescription,
        classificationPrompt:
            'Wipe the session: clear every places/routes/ranges entry, reset POIs/traffic configs, revert to standard style. Use only when the user asks for a clean slate.',
        inputSchema: resetStateSchema,
        outputSchema: resetStateOutputSchema,
        execute: executeResetState,
        tags: ['state', 'reset', 'destructive'],
        examples: ['resetState()'],
        examplePrompts: ['Start over', 'Reset everything', 'Clear all my data and the map'],
        relatedTools: ['recallState', 'clearMap'],
    },
    setEntryMode: {
        description: setEntryModeDescription,
        classificationPrompt:
            'Switch a slice (places/routes/ranges) between `multiple` (overlay several entries) and `single` (latest only). `single` drops older entries.',
        inputSchema: setEntryModeSchema,
        outputSchema: setEntryModeOutputSchema,
        execute: executeSetEntryMode,
        tags: ['state', 'mode', 'display'],
        examples: [
            'setEntryMode({ slice: "places", mode: "single" })',
            'setEntryMode({ slice: "routes", mode: "multiple" })',
        ],
        examplePrompts: [
            'Only show one route at a time',
            'Let me overlay multiple places searches',
            'Switch ranges back to single mode',
        ],
        relatedTools: ['recallState', 'recallPlaces', 'recallRoutes', 'recallRanges'],
    },
} satisfies Record<string, ToolDefinition>;

// Narrow the value type so the emitted d.ts captures only the keys, not the
// inlined `z.infer<...>` signatures from each `execute` (which the d.ts bundler
// flattens to invalid `infer<typeof X>` syntax). Must go through an intermediate
// const so TypeScript resolves the mapped type before re-exporting.
const DEFAULT_TOOLS_TYPED: { [K in keyof typeof defaultTools]: ToolDefinition } = defaultTools;

/**
 * Default tool set for the agent toolkit. Each entry is a {@link ToolDefinition}
 * — either a static `ToolEntry` or a `ToolEntryBuilder` that tailors the tool to
 * {@link ToolBuildOptions} (e.g. feature flags) at agent-creation time.
 *
 * Included automatically by createMapAgent unless includeDefaultTools is false.
 * Use resolveTools() for manual composition outside createMapAgent.
 *
 * @group Agent Toolkit
 */
export const DEFAULT_TOOLS = DEFAULT_TOOLS_TYPED;

/**
 * Union of all default tool names.
 *
 * @group Agent Toolkit
 */
export type ToolName = keyof typeof DEFAULT_TOOLS;

/**
 * All valid default tool names, derived from {@link DEFAULT_TOOLS}.
 *
 * @group Agent Toolkit
 */
export const TOOL_NAMES = Object.keys(DEFAULT_TOOLS) as ToolName[];
